export const concourseCss = `
@font-face{font-family:Concourse Sans;src:url('/templates/concourse/zalando-sans-latin.woff2') format('woff2');font-display:swap;font-weight:100 900}
.cq.ud-section{font-family:'Concourse Sans',Arial,sans-serif;color:var(--ud-fg,#0d1018);background:var(--ud-bg,#fff);line-height:1.55;isolation:isolate}
.cq .ud-container{max-width:1240px}.cq h1,.cq h2,.cq h3,.cq p,.cq blockquote{margin:0}.cq a{color:inherit;text-decoration:none}.cq button{font:inherit;cursor:pointer}.cq :focus-visible{outline:3px solid #7896ff;outline-offset:5px}.cq-head{max-width:790px;margin-bottom:46px}.cq-kicker{font-size:14px;margin-bottom:20px!important;color:inherit;opacity:.7}.cq-title{font-family:'Concourse Sans',Arial,sans-serif;font-size:clamp(34px,4.6vw,60px);font-weight:400;letter-spacing:-.045em;line-height:1.07;white-space:pre-line;text-wrap:balance}.cq-description{max-width:680px;margin-top:24px!important;font-size:18px;color:inherit;opacity:.68}.cq-button{display:inline-flex;align-items:center;justify-content:center;gap:26px;padding:14px 23px;border-radius:5px;background:#0d1018;color:white!important;font-size:15px;transition:transform .25s,background .25s}.cq-button:hover{transform:translateY(-3px);background:#293347}.cq-text-link{display:inline-block;margin-top:20px;border-bottom:1px solid #b5bbc4;padding-bottom:5px;font-size:14px}
.cq.cq-nav-wrap{color:white}.cq-nav-wrap--sticky.cq-nav-wrap--sticky{position:sticky;top:0;z-index:70}.cq-announcement{text-align:center;font-size:12px;padding:5px 20px;border-bottom:1px solid #ffffff12}.cq-nav{max-width:1240px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:30px;padding:20px 30px;background:linear-gradient(120deg,#ffffff0c,#ffffff05);backdrop-filter:blur(20px)}.cq-wordmark{font-size:20px;letter-spacing:-.04em;font-weight:650;white-space:nowrap}.cq-wordmark>span+span{border:1px solid currentColor;border-radius:2px;display:inline-flex;width:21px;height:21px;align-items:center;justify-content:center;margin-left:4px}.cq-links{display:flex;align-items:center;gap:30px;font-size:14px}.cq-links>a:not(.cq-button){opacity:.8}.cq-links>a:hover{opacity:1}.cq-links .cq-button{background:white;color:#0d1018!important;padding:9px 18px}.cq-menu{display:none;background:none;border:0;color:inherit}
.cq.cq-hero{position:relative;overflow:hidden}.cq.cq-hero--cinematic{color:white;min-height:650px}.cq-hero-media,.cq-hero-shade{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;z-index:-2}.cq-hero-shade{z-index:-1;background:linear-gradient(0deg,#0d1018 0%,#0d101884 27%,#0d101828 85%)}.cq-hero-copy{position:relative;z-index:1;max-width:850px}.cq-hero .cq-title{font-size:clamp(54px,7.5vw,104px);line-height:.98;letter-spacing:-.05em}.cq-hero .cq-head{margin-bottom:32px}.cq-hero .cq-description{opacity:.85}.cq-hero--cinematic .cq-button{background:#fff;color:#0d1018!important}.cq-motion-toggle{position:absolute;bottom:18px;right:24px;border:1px solid #ffffff60;border-radius:4px;padding:6px 10px;background:#0d101855;color:#fff;font-size:11px!important}.cq-hero--plain .cq-hero-copy{max-width:980px}
.cq.cq-logos{color:#fff}.cq-logos .ud-container{display:flex;align-items:center;gap:50px}.cq-logos h2{font-size:11px;text-transform:uppercase;font-weight:500;width:235px;flex-shrink:0;opacity:.55}.cq-marquee{overflow:hidden;mask-image:linear-gradient(90deg,transparent,#000 6%,#000 94%,transparent)}.cq-marquee>div{display:flex;width:max-content}.cq-logo-group{display:flex;gap:65px;padding-right:65px;align-items:center}.cq-logo-group span{white-space:nowrap;font-size:23px;font-weight:600;opacity:.6}.cq-logo-group img{max-height:30px;max-width:130px;object-fit:contain}.cq-marquee--moving>div{animation:cq-marquee 35s linear infinite}.cq-marquee:hover>div{animation-play-state:paused}@keyframes cq-marquee{to{transform:translateX(-50%)}}
.cq-cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:30px}.cq-cards--two{grid-template-columns:repeat(2,minmax(0,1fr))}.cq-card{min-width:0;padding-bottom:24px;border-bottom:1px solid #0d101820}.cq-card .ud-media{height:330px;overflow:hidden;margin-bottom:20px;border-radius:0}.cq-card img{width:100%;height:100%;object-fit:cover;transition:transform .7s}.cq-card:hover img{transform:scale(1.035)}.cq-card h3{font-size:20px;font-weight:500;letter-spacing:-.02em;margin-bottom:8px}.cq-card p{font-size:15px;color:#777984;max-width:550px}.cq-cards--two .cq-card{padding:26px 0 36px}.cq-cards--two .cq-card h3{font-size:30px}
.cq.cq-statement{color:white;overflow:hidden;position:relative;min-height:620px;display:flex;align-items:center}.cq-statement .ud-container{width:100%}.cq-statement-copy{position:relative;z-index:1;max-width:700px;margin:auto;text-align:center}.cq-statement .cq-button{background:white;color:#0d1018!important}.cq-architecture{position:absolute;inset:0;display:flex;justify-content:center;gap:0;opacity:.45;pointer-events:none}.cq-architecture i{display:block;width:15%;height:100%;background:linear-gradient(110deg,#ffffff05,#ffffff15 50%,#0003 51%);border-left:1px solid #ffffff09;transform:skewY(-15deg);animation:cq-light 8s ease-in-out infinite alternate}.cq-architecture i:nth-child(even){animation-delay:-4s}@keyframes cq-light{to{opacity:.2;transform:skewY(-15deg) translateY(25px)}}
.cq-agent-grid,.cq-security{display:grid;grid-template-columns:1fr 1fr;gap:70px}.cq-agent{border-top:1px solid #0d101824}.cq-agent button{width:100%;background:none;border:0;padding:24px 0;display:flex;justify-content:space-between;text-align:left;font-size:22px;letter-spacing:-.025em;color:inherit}.cq-agent p{font-size:15px;color:#777984;padding-bottom:28px;max-width:430px}.cq-agent.is-active{border-color:#0d1018}.cq-agent-visual{background:linear-gradient(140deg,#e7ebf0,#f8fafc);padding:40px;display:flex;flex-direction:column;justify-content:center;animation:cq-enter .5s ease}.cq-report{background:white;padding:25px;box-shadow:0 12px 50px #0d10180c;border:1px solid #0d10180a;border-radius:7px;transform:rotate(-2deg)}.cq-status{font-size:11px;color:#40776b}.cq-report h3{font-size:18px;margin:15px 0}.cq-chart{display:flex;align-items:flex-end;gap:10px;height:150px;border-bottom:1px solid #ddd;padding:8px 5px}.cq-chart i{flex:1;background:linear-gradient(#687d9d,#172742);border-radius:3px 3px 0 0;transform-origin:bottom;animation:cq-bars .6s both}.cq-report-line{display:flex;justify-content:space-between;font-size:11px;padding-top:12px;color:#777984}.cq-agent-result{display:flex;align-items:center;gap:20px;margin-top:30px}.cq-agent-result strong{font-size:56px;line-height:1;font-weight:400;letter-spacing:-.04em}.cq-agent-result span{font-size:13px;max-width:140px;color:#777984}@keyframes cq-bars{from{transform:scaleY(.1)}to{transform:scaleY(1)}}@keyframes cq-enter{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}
.cq-quote{border-top:1px solid #0d101824;padding-top:30px;animation:cq-enter .5s}.cq-quote blockquote{font-size:clamp(28px,3.7vw,48px);font-weight:400;letter-spacing:-.035em;line-height:1.23;max-width:1000px;margin:30px 0}.cq-quote>p{font-size:14px}.cq-quote p span{color:#777984}.cq-carousel-controls{display:flex;align-items:center;justify-content:flex-end;gap:18px;margin-top:30px;font-size:12px}.cq-carousel-controls button{border:1px solid #ccc;background:transparent;width:42px;height:42px;border-radius:50%;color:#0d1018}.cq-carousel-controls button:hover{background:#0d1018;color:white}
.cq-stat-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:30px;margin-top:60px}.cq-stat-grid>div{border-top:1px solid #0d101833;padding-top:30px}.cq-stat-grid strong{font-size:clamp(42px,5vw,72px);font-weight:400;letter-spacing:-.05em;line-height:1}.cq-stat-grid p{font-size:14px;color:#777984;margin-top:20px}.cq-security-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;align-content:center}.cq-security-grid>div{text-align:center;min-height:140px;background:#f5f6f8;display:flex;flex-direction:column;justify-content:center;padding:15px}.cq-security-grid span{font-size:36px;color:#53637f}.cq-security-grid p{font-size:12px;margin-top:15px}.cq.cq-closing{color:white;text-align:center}.cq-closing .cq-head{margin:0 auto 35px;max-width:900px}.cq-closing .cq-button{background:white;color:#0d1018!important}.cq-closing .cq-title{font-size:clamp(40px,6vw,80px)}.cq.cq-footer{color:white}.cq-footer-top{display:grid;grid-template-columns:1fr 1fr;gap:60px}.cq-footer-top p{color:#86878b;font-size:14px;margin-top:20px}.cq-footer nav{display:grid;grid-template-columns:repeat(3,1fr);gap:25px;font-size:14px}.cq-footer-bottom{border-top:1px solid #ffffff25;margin-top:70px;padding-top:24px;font-size:12px;color:#86878b;display:flex;justify-content:space-between;gap:20px}
@media(max-width:900px){.cq-links{gap:15px}.cq-agent-grid,.cq-security{gap:30px}.cq-card .ud-media{height:240px}.cq-cards{gap:20px}.cq-nav{padding:16px 24px}.cq-title{font-size:42px}}
@media(max-width:700px){.cq-menu{display:block}.cq-links{display:none;position:absolute;top:100%;left:0;right:0;background:#0d1018;padding:25px;z-index:20}.cq-links--open{display:flex;flex-direction:column;align-items:stretch}.cq-nav{position:relative}.cq-announcement{font-size:10px}.cq.cq-hero--cinematic{min-height:590px}.cq-hero .cq-title{font-size:60px}.cq-hero .cq-description{font-size:16px}.cq-title{font-size:36px}.cq-cards,.cq-cards--two,.cq-agent-grid,.cq-security,.cq-footer-top{grid-template-columns:1fr}.cq-card .ud-media{height:330px}.cq-logos .ud-container{display:block}.cq-logos h2{margin-bottom:20px;width:auto}.cq-agent-visual{padding:25px}.cq-stat-grid{grid-template-columns:repeat(2,1fr)}.cq-footer nav{grid-template-columns:repeat(2,1fr)}.cq-hero-copy{padding-top:0}.cq-security-grid{gap:10px}.cq-statement{min-height:500px}.cq-head{margin-bottom:32px}.cq-description{font-size:16px}}
@media(prefers-reduced-motion:reduce){.cq *, .cq *:before{animation:none!important;transition:none!important;scroll-behavior:auto!important}.cq-video{display:none}.cq-motion-toggle{display:none}}

.cq-closing{position:relative}
.cq-closing::before{content:'';position:absolute;inset:0;background:radial-gradient(ellipse at 50% 120%,rgba(255,255,255,.16),transparent 68%);pointer-events:none;z-index:0}
.cq-closing > *{position:relative;z-index:1}
`
