import type { BlockCategory } from '@uidesired/types'
import { quarryBlocks } from './blocks/quarry'
import {
  announceTessera,
  benefitsTessera,
  compareTessera,
  ctaBandTessera,
  faqTessera,
  footerTessera,
  heroTessera,
  logosTessera,
  metricsTessera,
  navbarTessera,
  pillarsTessera,
  principlesTessera,
  pricingTessera,
  rolesTessera,
  showcaseTessera,
  splitTessera,
} from './blocks/tessera'
import { navbarCentered, navbarCta, navbarSimple, navbarTransparent } from './blocks/navigation'
import { navbarIsland, navbarMinimal, navbarPill, navbarSplit, navbarUnderline, navbarUtility } from './blocks/navigation-extra'
import {
  heroBackground,
  heroBusiness,
  heroCentered,
  heroImage,
  heroPage,
  heroRestaurant,
  heroSaas,
  heroSplit,
} from './blocks/heroes'
import { featuresCards, featuresGrid, featuresIcons, featuresShowcase } from './blocks/features'
import { servicesCards, servicesGrid, servicesList } from './blocks/services'
import {
  contentCentered,
  contentImageText,
  contentRichtext,
  contentText,
  contentTextImage,
  contentTwoColumns,
} from './blocks/content'
import { commerceBuy } from './blocks/commerce'
import { funnelOptin } from './blocks/funnel'
import { galleryCarousel, galleryGrid, galleryLogos, galleryMasonry, galleryShowcase } from './blocks/gallery'
import { pricingComparison, pricingThree, pricingTwo } from './blocks/pricing'
import { faqAccordion, faqTwoColumn } from './blocks/faq'
import { ctaBackground, ctaSimple, ctaSplit } from './blocks/cta'
import { testimonialsCards, testimonialsCarousel, testimonialsFeatured } from './blocks/testimonials'
import { footerCentered, footerMulti, footerSimple } from './blocks/footers'
import { formAppointment, formContact, formLead, formNewsletter, formQuote } from './blocks/forms'
import { statsHighlight, statsRow } from './blocks/stats'
import { teamCards, teamSpotlight } from './blocks/team'
import { processSteps, processTimeline } from './blocks/process'
import { blogFeatured, blogList, blogMagazine, blogOverlay, blogPost } from './blocks/blog'
import { contentCapabilities, ctaBar, ctaGradient, galleryProjects, heroStudio, pricingDuo, testimonialsBento } from './blocks/studio'
import { featuresMinimal, heroProduct, teamCircle, testimonialsCompact } from './blocks/chatdeck'
import { featuresRail, heroGlow, processZigzag, testimonialsRail } from './blocks/genesis'
import { contentBand, contentMarkers, contentRuled, heroPanel, navbarCounsel } from './blocks/counsel'
import { contentHours, contentLocations, contentMap, contentSkills, contentVideo, ctaBanner, galleryCompare, postsCards, proofBar } from './blocks/extras'
import {
  ctaCrew,
  ctaVerdara,
  featuresVerdara,
  footerVerdara,
  heroVerdara,
  navbarVerdara,
  pricingVerdara,
  proofVerdara,
  testimonialsVerdara,
} from './blocks/verdara'
import {
  faqSolara,
  featuresSolara,
  footerSolara,
  heroSolara,
  navbarSolara,
  pricingSolara,
  statsSolara,
  teamSolara,
  testimonialsSolara,
} from './blocks/solara'
import {
  aboutMoksha,
  benefitsMoksha,
  ctaMoksha,
  faqMoksha,
  featuresMoksha,
  footerMoksha,
  heroMoksha,
  navbarMoksha,
  pricingMoksha,
  storyMoksha,
  testimonialsMoksha,
} from './blocks/moksha'
import {
  bentoCinder,
  contactCinder,
  coverageCinder,
  ctaCinder,
  footerCinder,
  galleryCinder,
  heroCinder,
  introCinder,
  journalCinder,
  navbarCinder,
  pricingCinder,
  processCinder,
  serviceListCinder,
  splitCinder,
  testimonialsCinder,
  tickerCinder,
  timelineCinder,
  valuesCinder,
} from './blocks/cinderrow'
import {
  aboutLumen,
  areaLumen,
  bookingLumen,
  contactLumen,
  ctaLumen,
  footerLumen,
  heroLumen,
  navbarLumen,
  pricingLumen,
  servicesLumen,
  valuesLumen,
} from './blocks/lumenlane'
import {
  contactAxiom,
  ctaAxiom,
  faqAxiom,
  footerAxiom,
  heroAxiom,
  heroAxiomPage,
  journalAxiom,
  navbarAxiom,
  pillarsAxiom,
  portfolioAxiom,
  principlesAxiom,
  processAxiom,
  projectsAxiom,
  proofAxiom,
  sectorsAxiom,
  servicesAxiom,
  statsAxiom,
  studioAxiom,
  teamAxiom,
  thesisAxiom,
  timelineAxiom,
  valuesAxiom,
} from './blocks/axiomnorth'
import {
  compareNorthbook,
  contactNorthbook,
  ctaBandNorthbook,
  footerNorthbook,
  galleryNorthbook,
  heroNorthbook,
  inlineCtaNorthbook,
  listNorthbook,
  logosNorthbook,
  navbarNorthbook,
  newsletterNorthbook,
  officesNorthbook,
  pageHeroNorthbook,
  personasNorthbook,
  postsNorthbook,
  resourcesNorthbook,
  richTextNorthbook,
  servicesNorthbook,
  splitNorthbook,
  statsNorthbook,
  teamNorthbook,
  testimonialsNorthbook,
  topbarNorthbook,
  valuesNorthbook,
} from './blocks/northbook'
import {
  caseStudiesVoltera,
  contactVoltera,
  ctaBandVoltera,
  customPlanVoltera,
  faqVoltera,
  featuredCaseVoltera,
  footerVoltera,
  heroVoltera,
  logosVoltera,
  mapVoltera,
  navbarVoltera,
  pageHeroVoltera,
  postsVoltera,
  pricingVoltera,
  processVoltera,
  richTextVoltera,
  serviceCardsVoltera,
  servicesVoltera,
  splitVoltera,
  statsBandVoltera,
  statsStripVoltera,
  teamVoltera,
  testimonialsVoltera,
  valuesVoltera,
  whyVoltera,
} from './blocks/voltera'
import {
  changelogHalcyon,
  compareHalcyon,
  contactHalcyon,
  ctaSceneHalcyon,
  faqColumnsHalcyon,
  featureRowHalcyon,
  footerHalcyon,
  heroHalcyon,
  logosHalcyon,
  manifestoHalcyon,
  navbarHalcyon,
  pageHeadHalcyon,
  priceCardHalcyon,
  principlesHalcyon,
  quoteHalcyon,
  richTextHalcyon,
  showcaseHalcyon,
  splitHalcyon,
  storyHalcyon,
  teamHalcyon,
} from './blocks/halcyon'
import {
  bandMeridian,
  bentoMeridian,
  casesMeridian,
  compareMeridian,
  contactMeridian,
  ctaMeridian,
  faqMeridian,
  footerMeridian,
  heroMeridian,
  logosMeridian,
  navbarMeridian,
  pageHeadMeridian,
  pillarsMeridian,
  positionsMeridian,
  pricingMeridian,
  resourcesMeridian,
  richTextMeridian,
  splitMeridian,
  statsMeridian,
} from './blocks/meridian'
import {
  accentAnchor,
  contactAnchor,
  ctaAnchor,
  faqAnchor,
  featureAnchor,
  footerAnchor,
  galleryAnchor,
  heroAnchor,
  introAnchor,
  navbarAnchor,
  officesAnchor,
  pageHeadAnchor,
  positionsAnchor,
  principlesAnchor,
  servicesAnchor,
  statsAnchor,
  stepsAnchor,
  topbarAnchor,
  trackAnchor,
} from './blocks/anchorline'
import {
  aboutAperture,
  blogAperture,
  contactAperture,
  ctaAperture,
  faqAperture,
  footerAperture,
  heroAperture,
  logosAperture,
  navbarAperture,
  pageHeadAperture,
  portfolioAperture,
  pricingAperture,
  processAperture,
  richtextAperture,
  servicesAperture,
  statsAperture,
  teamAperture,
  testimonialsAperture,
  tickerAperture,
} from './blocks/aperture'
import {
  articlesKindred,
  benefitsKindred,
  carouselKindred,
  companiesKindred,
  featuredKindred,
  filterKindred,
  footerKindred,
  heroKindred,
  jobsKindred,
  navbarKindred,
  numbersKindred,
  pageHeadKindred,
  promosKindred,
  richTextKindred,
  socialKindred,
  statsKindred,
  storyKindred,
  subnavKindred,
  valuesKindred,
  videoKindred,
} from './blocks/kindred'
import {
  accordionJunction,
  appHeroJunction,
  bannerJunction,
  cardsJunction,
  codeJunction,
  ctaBandJunction,
  faqJunction,
  footerJunction,
  heroJunction,
  includedJunction,
  logosJunction,
  metricsJunction,
  navbarJunction,
  platformJunction,
  pricingJunction,
  quoteJunction,
  secureJunction,
  splitJunction,
  statsJunction,
  stepsJunction,
  triggersJunction,
  useCasesJunction,
  workflowsJunction,
} from './blocks/junction'
import {
  aboutVantage,
  benefitsVantage,
  compareVantage,
  contactVantage,
  ctaCardVantage,
  faqVantage,
  footerVantage,
  heroVantage,
  integrationsVantage,
  journalVantage,
  mapVantage,
  navbarVantage,
  officesVantage,
  pageHeroVantage,
  pillarsVantage,
  pricingVantage,
  servicesVantage,
  sizingVantage,
  splitVantage,
  statsVantage,
  stepsVantage,
} from './blocks/vantage'
import {
  generatedCollection,
  generatedComposition,
  generatedCta,
  generatedFaq,
  generatedFooter,
  generatedForm,
  generatedHero,
  generatedMetrics,
  generatedNav,
  generatedPricing,
  generatedStory,
  generatedVoices,
} from './blocks/generated'
import type { BlockDefinition } from './types'

const blocks = [
  generatedNav,
  navbarSimple,
  navbarCentered,
  navbarCta,
  navbarTransparent,
  navbarPill,
  navbarSplit,
  navbarUnderline,
  navbarIsland,
  navbarUtility,
  navbarMinimal,
  navbarCounsel,
  navbarVerdara,
  navbarSolara,
  navbarMoksha,
  generatedHero,
  heroCentered,
  heroSplit,
  heroImage,
  heroBackground,
  heroSaas,
  heroPage,
  heroRestaurant,
  heroBusiness,
  heroStudio,
  heroProduct,
  heroGlow,
  heroPanel,
  heroVerdara,
  heroSolara,
  heroMoksha,
  generatedCollection,
  generatedComposition,
  featuresCards,
  featuresIcons,
  featuresGrid,
  featuresShowcase,
  featuresMinimal,
  featuresRail,
  proofVerdara,
  featuresVerdara,
  statsSolara,
  featuresSolara,
  aboutMoksha,
  featuresMoksha,
  benefitsMoksha,
  storyMoksha,
  statsRow,
  statsHighlight,
  proofBar,
  processSteps,
  processTimeline,
  processZigzag,
  servicesCards,
  servicesGrid,
  servicesList,
  generatedStory,
  contentText,
  contentRichtext,
  contentImageText,
  contentTextImage,
  contentCentered,
  contentTwoColumns,
  contentVideo,
  contentHours,
  contentSkills,
  contentMap,
  contentLocations,
  contentCapabilities,
  contentMarkers,
  contentBand,
  contentRuled,
  postsCards,
  blogList,
  blogFeatured,
  blogMagazine,
  blogOverlay,
  blogPost,
  galleryGrid,
  galleryMasonry,
  galleryCarousel,
  galleryLogos,
  galleryShowcase,
  funnelOptin,
  commerceBuy,
  galleryCompare,
  galleryProjects,
  pricingTwo,
  pricingThree,
  pricingComparison,
  pricingDuo,
  pricingVerdara,
  pricingSolara,
  pricingMoksha,
  generatedPricing,
  faqAccordion,
  faqTwoColumn,
  faqSolara,
  faqMoksha,
  generatedFaq,
  generatedCta,
  ctaSimple,
  ctaSplit,
  ctaBackground,
  ctaBanner,
  ctaBar,
  ctaGradient,
  ctaCrew,
  ctaVerdara,
  ctaMoksha,
  generatedVoices,
  testimonialsCards,
  testimonialsCarousel,
  testimonialsFeatured,
  testimonialsBento,
  testimonialsCompact,
  testimonialsRail,
  testimonialsVerdara,
  testimonialsSolara,
  testimonialsMoksha,
  teamCards,
  teamCircle,
  teamSpotlight,
  teamSolara,
  generatedMetrics,
  generatedForm,
  formContact,
  formLead,
  formNewsletter,
  formQuote,
  formAppointment,
  generatedFooter,
  footerSimple,
  footerCentered,
  footerMulti,
  footerVerdara,
  footerSolara,
  footerMoksha,
  navbarCinder,
  heroCinder,
  introCinder,
  bentoCinder,
  splitCinder,
  tickerCinder,
  coverageCinder,
  testimonialsCinder,
  galleryCinder,
  serviceListCinder,
  pricingCinder,
  processCinder,
  timelineCinder,
  valuesCinder,
  journalCinder,
  contactCinder,
  ctaCinder,
  footerCinder,
  navbarLumen,
  heroLumen,
  servicesLumen,
  valuesLumen,
  pricingLumen,
  aboutLumen,
  areaLumen,
  contactLumen,
  bookingLumen,
  ctaLumen,
  footerLumen,
  navbarAxiom,
  heroAxiom,
  heroAxiomPage,
  statsAxiom,
  proofAxiom,
  principlesAxiom,
  pillarsAxiom,
  portfolioAxiom,
  journalAxiom,
  ctaAxiom,
  footerAxiom,
  valuesAxiom,
  timelineAxiom,
  teamAxiom,
  thesisAxiom,
  sectorsAxiom,
  processAxiom,
  studioAxiom,
  projectsAxiom,
  servicesAxiom,
  faqAxiom,
  contactAxiom,
  navbarVantage,
  heroVantage,
  pageHeroVantage,
  aboutVantage,
  servicesVantage,
  statsVantage,
  pillarsVantage,
  splitVantage,
  stepsVantage,
  integrationsVantage,
  benefitsVantage,
  journalVantage,
  pricingVantage,
  compareVantage,
  faqVantage,
  ctaCardVantage,
  sizingVantage,
  contactVantage,
  mapVantage,
  officesVantage,
  footerVantage,
  navbarJunction,
  heroJunction,
  appHeroJunction,
  bannerJunction,
  cardsJunction,
  splitJunction,
  accordionJunction,
  secureJunction,
  stepsJunction,
  useCasesJunction,
  workflowsJunction,
  triggersJunction,
  codeJunction,
  statsJunction,
  metricsJunction,
  quoteJunction,
  logosJunction,
  pricingJunction,
  includedJunction,
  platformJunction,
  faqJunction,
  ctaBandJunction,
  footerJunction,
  navbarKindred,
  subnavKindred,
  heroKindred,
  pageHeadKindred,
  carouselKindred,
  companiesKindred,
  articlesKindred,
  featuredKindred,
  filterKindred,
  storyKindred,
  valuesKindred,
  statsKindred,
  numbersKindred,
  videoKindred,
  benefitsKindred,
  jobsKindred,
  promosKindred,
  socialKindred,
  richTextKindred,
  footerKindred,
  topbarNorthbook,
  navbarNorthbook,
  heroNorthbook,
  pageHeroNorthbook,
  servicesNorthbook,
  listNorthbook,
  splitNorthbook,
  statsNorthbook,
  logosNorthbook,
  resourcesNorthbook,
  testimonialsNorthbook,
  personasNorthbook,
  inlineCtaNorthbook,
  compareNorthbook,
  valuesNorthbook,
  teamNorthbook,
  officesNorthbook,
  galleryNorthbook,
  richTextNorthbook,
  postsNorthbook,
  newsletterNorthbook,
  contactNorthbook,
  ctaBandNorthbook,
  footerNorthbook,
  navbarVoltera,
  heroVoltera,
  pageHeroVoltera,
  servicesVoltera,
  serviceCardsVoltera,
  processVoltera,
  statsBandVoltera,
  statsStripVoltera,
  splitVoltera,
  whyVoltera,
  valuesVoltera,
  teamVoltera,
  featuredCaseVoltera,
  caseStudiesVoltera,
  testimonialsVoltera,
  pricingVoltera,
  customPlanVoltera,
  faqVoltera,
  postsVoltera,
  richTextVoltera,
  ctaBandVoltera,
  contactVoltera,
  mapVoltera,
  logosVoltera,
  footerVoltera,
  navbarHalcyon,
  heroHalcyon,
  pageHeadHalcyon,
  featureRowHalcyon,
  showcaseHalcyon,
  splitHalcyon,
  quoteHalcyon,
  logosHalcyon,
  compareHalcyon,
  priceCardHalcyon,
  faqColumnsHalcyon,
  principlesHalcyon,
  manifestoHalcyon,
  teamHalcyon,
  storyHalcyon,
  changelogHalcyon,
  richTextHalcyon,
  contactHalcyon,
  ctaSceneHalcyon,
  footerHalcyon,
  navbarMeridian,
  heroMeridian,
  pageHeadMeridian,
  logosMeridian,
  bentoMeridian,
  statsMeridian,
  casesMeridian,
  splitMeridian,
  pillarsMeridian,
  pricingMeridian,
  compareMeridian,
  faqMeridian,
  resourcesMeridian,
  positionsMeridian,
  bandMeridian,
  ctaMeridian,
  richTextMeridian,
  contactMeridian,
  footerMeridian,
  topbarAnchor,
  navbarAnchor,
  heroAnchor,
  pageHeadAnchor,
  introAnchor,
  servicesAnchor,
  featureAnchor,
  principlesAnchor,
  accentAnchor,
  statsAnchor,
  stepsAnchor,
  galleryAnchor,
  trackAnchor,
  contactAnchor,
  officesAnchor,
  positionsAnchor,
  faqAnchor,
  ctaAnchor,
  footerAnchor,
  navbarAperture,
  heroAperture,
  pageHeadAperture,
  logosAperture,
  aboutAperture,
  statsAperture,
  servicesAperture,
  portfolioAperture,
  processAperture,
  tickerAperture,
  testimonialsAperture,
  teamAperture,
  pricingAperture,
  faqAperture,
  blogAperture,
  ctaAperture,
  contactAperture,
  richtextAperture,
  footerAperture,
  announceTessera,
  navbarTessera,
  heroTessera,
  showcaseTessera,
  pillarsTessera,
  splitTessera,
  metricsTessera,
  logosTessera,
  pricingTessera,
  compareTessera,
  faqTessera,
  principlesTessera,
  benefitsTessera,
  rolesTessera,
  ctaBandTessera,
  footerTessera,
  ...quarryBlocks,
]

export const blockRegistry: Record<string, BlockDefinition> = Object.fromEntries(
  blocks.map((block) => [block.type, block]),
)

export const BLOCK_CATEGORIES: BlockCategory[] = [
  'navigation',
  'hero',
  'features',
  'services',
  'content',
  'gallery',
  'pricing',
  'faq',
  'cta',
  'testimonials',
  'team',
  'blog',
  'form',
  'footer',
]

export const TYPE_ALIASES: Record<string, string> = {
  'nav.simple': 'navbar.simple',
  'nav.centered': 'navbar.centered',
  'nav.cta': 'navbar.cta',
  'nav.transparent': 'navbar.transparent',
  'header.simple': 'navbar.simple',
  'header.centered': 'navbar.centered',
  'nav.generated': 'generated.nav',
  'footer.generated': 'generated.footer',
}

export function getBlock(type: string): BlockDefinition | undefined {
  return blockRegistry[type] ?? blockRegistry[TYPE_ALIASES[type]]
}

export function listBlocks(filter?: { category?: BlockCategory }): BlockDefinition[] {
  const all = Object.values(blockRegistry)
  if (!filter?.category) return all
  return all.filter((block) => block.category === filter.category)
}

export function blockTypes(): string[] {
  return Object.keys(blockRegistry)
}
