export const velouraCss = `
.vl{font-family:var(--font-body,Inter,sans-serif);font-size:16px;line-height:1.65;color:var(--ud-fg,var(--color-text,#1d261b));}
.vl h1,.vl h2,.vl h3{color:var(--ud-heading,inherit);font-family:var(--font-heading,Inter,sans-serif);font-weight:var(--font-heading-weight,600);letter-spacing:-.055em;line-height:1.12;white-space:pre-line;overflow-wrap:anywhere;}
.vl h1{font-size:clamp(44px,5.8vw,86px);margin:0}.vl h2{font-size:clamp(34px,4vw,58px);margin:0}.vl h3{font-size:26px;margin:18px 0 10px;letter-spacing:-.035em}
.vl p{white-space:pre-line}.vl a{color:inherit;text-decoration:none}.vl button,.vl summary{cursor:pointer}.vl button{font:inherit}.vl :is(a,button,summary):focus-visible{outline:3px solid #bd7600;outline-offset:5px}.vl .vl-head{max-width:760px;margin-bottom:36px}.vl-eyebrow{font-size:14px;font-weight:600;letter-spacing:.1em;margin-bottom:24px}.vl-eyebrow p{margin:0}.vl-lead{max-width:580px;margin:24px 0 0;opacity:.85}.vl-button{display:inline-flex;align-items:center;justify-content:space-between;gap:30px;background:var(--color-primary,#fabb0e);color:var(--color-text,#1d261b);padding:16px 23px;border-radius:12px;font-weight:600;line-height:1.4;transition:transform .2s}.vl-button:hover{transform:translateY(-2px)}.vl-button>span:last-child{font-size:23px}.vl-brand{display:inline-flex;align-items:center;gap:9px;font-size:36px;font-weight:600;letter-spacing:-.065em;line-height:1.2}.vl-brand>span:last-child{color:var(--color-primary,#fabb0e)}
.vl-nav{z-index:40}.vl-sticky.vl-sticky{position:sticky;top:0;z-index:70}.vl-nav-inner{display:flex;align-items:center;justify-content:space-between;gap:25px}.vl-nav nav{display:flex;flex-wrap:wrap;gap:20px;font-size:14px}.vl-nav nav a:hover,.vl-footer nav a:hover{text-decoration:underline;text-underline-offset:5px}.vl-nav .vl-button{padding:12px 18px;font-size:14px}.vl-menu{display:none;color:inherit;background:transparent;border:1px solid currentColor;border-radius:8px;padding:8px 12px}
.vl-hero-grid{display:grid;grid-template-columns:1fr 1fr;max-width:1600px;margin:auto}.vl-hero-copy{padding:80px clamp(24px,5vw,90px);align-self:center}.vl-hero-note{display:flex;align-items:center;gap:15px;font-size:14px;margin-top:27px;max-width:340px}.vl-hero-note>span{color:var(--color-primary,#fabb0e);font-size:42px}.vl-hero-photo{position:relative;min-height:620px}.vl-hero-photo>.ud-media{height:100%;border-radius:0}.vl-hero-photo img{height:100%;object-fit:cover}.vl-photo-caption{position:absolute;bottom:0;right:0;max-width:85%;display:flex;gap:28px;align-items:center;padding:22px 30px;border-radius:16px 0 0;background:var(--color-background,#f5f0f0);color:var(--color-text,#1d261b);font-size:14px;font-weight:600;letter-spacing:.06em}.vl-photo-caption>span:last-child{font-size:24px}.vl-page-header{text-align:center}.vl-page-header .vl-head{margin:auto;max-width:850px}.vl-page-header .vl-lead{margin:24px auto 0}
.vl-split{display:grid;grid-template-columns:1fr 1fr;gap:clamp(32px,6vw,90px);align-items:center}.vl-reverse>:first-child{order:2}.vl-story-photo .ud-media{border-radius:15px}.vl-cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:25px}.vl-service{border:1px solid #1d261b25;border-radius:15px;overflow:hidden}.vl-service .ud-media{border-radius:0}.vl-card-body{padding:26px}.vl-number{display:flex;gap:8px;font-size:14px}.vl-service summary{display:flex;justify-content:space-between;gap:16px;border-top:1px solid #1d261b25;padding:18px 0 0;margin-top:25px;font-weight:600;list-style:none}.vl-service details[open] summary{margin-bottom:12px}.vl-service details .vl-button{margin-top:12px}.vl-step{display:inline-grid;place-items:center;width:62px;height:62px;border:1px solid currentColor;border-radius:50%;font-size:23px}.vl-process .vl-cards{gap:50px;margin-top:55px}
.vl-filters{display:flex;flex-wrap:wrap;gap:10px;margin:0 0 30px}.vl-filters button{background:transparent;border:1px solid #1d261b50;border-radius:30px;padding:9px 24px;color:inherit}.vl-filters button[aria-pressed=true]{background:var(--color-text,#1d261b);color:var(--color-background,#f5f0f0)}.vl-gallery{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:26px;margin-bottom:35px}.vl-gallery figure{margin:0}.vl-gallery figure:nth-child(3n+2){padding-top:60px}.vl-gallery .ud-media{border-radius:15px}.vl-gallery figcaption{display:flex;justify-content:space-between;gap:12px;font-size:14px;padding-top:14px}.vl-gallery figcaption>span:first-child{font-weight:600}.vl-team{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:24px}.vl-team .ud-media{border-radius:15px}.vl-team h3{font-size:24px}.vl-team summary{font-size:14px}.vl-team details p{font-size:16px}.vl-testimonials blockquote{font-size:clamp(22px,2.5vw,32px);line-height:1.4;margin:20px 0}.vl-stars{color:var(--color-primary,#fabb0e);letter-spacing:5px}.vl-arrows{display:flex;gap:20px;align-items:center;margin-top:28px}.vl-arrows button{border:1px solid currentColor;background:transparent;color:inherit;border-radius:50%;width:48px;height:48px;font-size:22px}.vl-price-list article{display:flex;align-items:baseline;gap:25px;justify-content:space-between;border-bottom:1px solid #1d261b30;padding:12px 0}.vl-price-list article>span{white-space:nowrap;font-weight:600}.vl-price-list h3{font-size:23px}.vl-price-list p{font-size:14px}.vl-faq details{border-bottom:1px solid #1d261b30;padding:23px 0}.vl-faq summary{display:flex;justify-content:space-between;gap:20px;font-size:19px;font-weight:600;list-style:none}.vl-faq summary::-webkit-details-marker{display:none}.vl-faq details[open] summary>span:last-child{transform:rotate(45deg)}.vl-cta{text-align:center}.vl-cta .vl-head{margin:0 auto 30px}.vl-cta .vl-lead{margin:24px auto 0}.vl-cta .vl-button{background:var(--color-text,#1d261b);color:var(--color-background,#f5f0f0)}
.vl-form{background:var(--color-surface,#fdfcfc);color:var(--color-text,#1d261b);padding:35px;border-radius:15px}.vl-form>p{font-size:14px;margin-top:22px}.vl-form input,.vl-form textarea{width:100%;font:inherit}.vl-contact-info{display:grid;gap:8px}.vl-contact-info h3{font-size:20px}.vl-footer-top{display:flex;gap:35px;align-items:center;justify-content:space-between}.vl-footer nav{display:flex;flex-wrap:wrap;gap:26px;margin:40px 0;padding:28px 0;border-top:1px solid #ffffff40;border-bottom:1px solid #ffffff40}.vl-footer>.ud-container>p:last-child{font-size:14px;opacity:.7}
@container udpage (max-width:1000px){.vl-nav nav{gap:12px}.vl-nav-cta{display:none}.vl-hero-copy{padding:55px 30px}.vl-hero h1{font-size:56px}.vl-hero-photo{min-height:560px}.vl-team{grid-template-columns:repeat(2,minmax(0,1fr))}.vl-card-body{padding:20px}.vl-cards{gap:16px}}
@container udpage (max-width:700px){.vl h1{font-size:46px}.vl h2{font-size:36px}.vl-nav-inner{flex-wrap:wrap}.vl-menu{display:block}.vl-nav nav{display:none;width:100%;flex-direction:column;padding:15px 0}.vl-nav nav.is-open{display:flex}.vl-hero-grid,.vl-split,.vl-cards{grid-template-columns:1fr}.vl-hero-copy{padding:48px 24px}.vl-hero-photo{min-height:0}.vl-hero-photo>.ud-media{max-height:520px}.vl-gallery{grid-template-columns:1fr 1fr;gap:18px}.vl-gallery figure:nth-child(3n+2){padding-top:0}.vl-gallery figcaption{flex-direction:column;gap:2px}.vl-reverse>:first-child{order:0}.vl-team{gap:18px}.vl-team h3{font-size:21px}.vl-form{padding:24px}.vl-footer-top{align-items:flex-start;flex-direction:column}.vl .vl-head{margin-bottom:28px}.vl-process .vl-cards{gap:30px}.vl-price-list article{flex-wrap:wrap;gap:0}.vl-price-list article>span{margin-bottom:16px}}
@media(prefers-reduced-motion:reduce){.vl *{transition:none!important;animation:none!important}}
`


