import { useState } from 'react'
import { EditableText, editOf } from '../editable'
import { BrandLogo, Media, SafeText, SectionShell, bool, cx, items, str, type Props } from '../primitives'
import { headFields, image, link, logoImageFields, navLinksField, repeater, schema, select, stickyField, text, textarea, toggle } from '../schema'
import { defineBlock } from '../types'

const asset = (name: string) => `/templates/concourse/${name}`
const base = { paddingTop: 104, paddingBottom: 104, animation: 'fade-up', animationDuration: 800, animationTrigger: 'scroll' }
const cta = [text('buttonLabel', 'Button label', { styleTarget: 'button' }), link('buttonUrl', 'Button link')]
const cardFields = [text('title', 'Title'), textarea('description', 'Description'), image('image', 'Image'), link('url', 'Link')]
const agents = [
  { title: 'Flux & Variance Agent', description: 'Understand the drivers behind every change. Compare actuals against your plan, investigate exceptions, and turn findings into clear commentary.', result: 'Variance analysis', value: '75%', metric: 'Less repetitive work' },
  { title: 'Close Agent', description: 'Bring reconciliations, supporting evidence, and outstanding actions into one coordinated workflow.', result: 'Month-end checklist', value: '20+', metric: 'Hours returned to your team' },
  { title: 'Forecast Agent', description: 'Build a living forecast from operational signals and explore the assumptions behind each scenario.', result: 'Rolling forecast', value: '6×', metric: 'More room for analysis' },
  { title: 'AR & Collections Agent', description: 'Prioritize overdue accounts, prepare outreach, and give your team a clear view of incoming cash.', result: 'Collections overview', value: '24/7', metric: 'Visibility into your workflow' },
  { title: 'Business Review Agent', description: 'Bring the week’s performance into a concise review with connected evidence and recommended next steps.', result: 'Weekly performance', value: 'One', metric: 'Connected view of performance' },
]
function Head({ p, hero = false }: { p: Props; hero?: boolean }) {
  return <header className="cq-head"><EditableText edit={editOf(p)} path={['eyebrow']} value={str(p.eyebrow)} as="p" className="cq-kicker" /><EditableText edit={editOf(p)} path={['heading']} value={str(p.heading)} as={hero ? 'h1' : 'h2'} className="cq-title" /><SafeText value={p.description} edit={editOf(p)} path={['description']} className="cq-description" /></header>
}
function Cta({ p }: { p: Props }) { return str(p.buttonLabel) ? <a className="cq-button" href={str(p.buttonUrl, '/company#contact')}><EditableText edit={editOf(p)} path={['buttonLabel']} value={str(p.buttonLabel)} as="span" /><span aria-hidden="true">↗</span></a> : null }
function Nav(p: Props) {
  const [open, setOpen] = useState(false)
  return <SectionShell props={p} tone="primary" className={cx('cq', 'cq-nav-wrap', bool(p.sticky, true) && 'cq-nav-wrap--sticky')} bleed><div className="cq-announcement"><EditableText edit={editOf(p)} path={['announcement']} value={str(p.announcement)} as="span" /></div><div className="cq-nav"><a className="cq-wordmark" href="/"><BrandLogo props={p} alt={str(p.brand)}><EditableText edit={editOf(p)} path={['brand']} value={str(p.brand)} as="span" /></BrandLogo> <span aria-hidden="true">↗</span></a><button type="button" className="cq-menu" aria-expanded={open} aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? 'Close' : 'Menu'} ☰</button><nav aria-label="Main navigation" className={open ? 'cq-links cq-links--open' : 'cq-links'}>{items(p.links, []).map((l, i) => <a key={i} href={str(l.url)} onClick={() => setOpen(false)}>{str(l.label)}</a>)}<Cta p={p} /></nav></div></SectionShell>
}
function Hero(p: Props) {
  const [paused, setPaused] = useState(false)
  const cinematic = str(p.layout, 'cinematic') === 'cinematic'
  return <SectionShell props={p} tone={cinematic ? 'primary' : 'surface'} bleed className={`cq cq-hero ${cinematic ? 'cq-hero--cinematic' : 'cq-hero--plain'}`}>
    {cinematic && <><img className="cq-hero-media" src={str(p.image)} alt="" />{str(p.video) && !editOf(p) && !paused && <video className="cq-hero-media cq-video" autoPlay muted loop playsInline poster={str(p.image)} src={str(p.video)} aria-hidden="true" />}<div className="cq-hero-shade" /></>}
    <div className="ud-container"><div className="cq-hero-copy"><Head p={p} hero /><Cta p={p} /></div></div>
    {cinematic && str(p.video) && <button className="cq-motion-toggle" type="button" aria-label={paused ? 'Play background video' : 'Pause background video'} onClick={() => setPaused(!paused)}>{paused ? 'Play motion' : 'Pause motion'}</button>}
  </SectionShell>
}
function Cards(p: Props) { return <SectionShell props={p} className="cq"><Head p={p} /><div className={`cq-cards cq-cards--${str(p.layout, 'three')}`}>{items(p.items, []).map((item, i) => <article key={i} className="cq-card">{str(item.image) && <Media src={str(item.image)} alt={str(item.title)} edit={editOf(p)} path={['items', i, 'image']} />}<EditableText edit={editOf(p)} path={['items', i, 'title']} value={str(item.title)} as="h3" /><SafeText value={item.description} edit={editOf(p)} path={['items', i, 'description']} />{str(item.url) && <a className="cq-text-link" href={str(item.url)}>Explore <span aria-hidden="true">↗</span></a>}</article>)}</div></SectionShell> }
function Agents(p: Props) {
  const [active, setActive] = useState(0)
  const entries = items(p.items, [])
  const selected = entries[Math.min(active, Math.max(entries.length - 1, 0))]
  return <SectionShell props={p} className="cq"><Head p={p} /><div className="cq-agent-grid"><div>{entries.map((entry, i) => <div className={`cq-agent ${active === i ? 'is-active' : ''}`} key={i}><button type="button" aria-expanded={active === i} onClick={() => setActive(i)}><span>{str(entry.title)}</span><span aria-hidden="true">{active === i ? '−' : '+'}</span></button>{active === i && <SafeText value={entry.description} edit={editOf(p)} path={['items', i, 'description']} />}</div>)}</div>{selected && <div className="cq-agent-visual" key={active}><div className="cq-report"><span className="cq-status">● Agent completed</span><h3>{str(selected.result)}</h3><div className="cq-chart" aria-label="Illustrative performance chart">{[32, 47, 39, 64, 56, 78, 91].map((height, i) => <i key={i} style={{ height: `${height}%`, animationDelay: `${i * 70}ms` }} />)}</div><div className="cq-report-line"><span>Connected evidence</span><span>Verified ✓</span></div><div className="cq-report-line"><span>Ready for review</span><span>Just now</span></div></div><div className="cq-agent-result"><strong>{str(selected.value)}</strong><span>{str(selected.metric)}</span></div></div>}</div></SectionShell>
}
function Quotes(p: Props) {
  const [active, setActive] = useState(0)
  const entries = items(p.items, [])
  const index = Math.min(active, Math.max(entries.length - 1, 0))
  const entry = entries[index]
  return <SectionShell props={p} tone="surface" className="cq cq-quotes"><Head p={p} />{entry && <><div className="cq-quote" key={index}><span className="cq-kicker">{str(entry.company)}</span><blockquote><EditableText edit={editOf(p)} path={['items', index, 'quote']} value={str(entry.quote)} as="p" /></blockquote><p>{str(entry.name)} <span> / {str(entry.role)}</span></p></div><div className="cq-carousel-controls"><button type="button" aria-label="Previous testimonial" onClick={() => setActive((index - 1 + entries.length) % entries.length)}>←</button><span>{index + 1} / {entries.length}</span><button type="button" aria-label="Next testimonial" onClick={() => setActive((index + 1) % entries.length)}>→</button></div></>}</SectionShell>
}
export const concourseBlocks = [
  defineBlock({ type: 'navbar.concourse', version: 1, category: 'navigation', label: 'Concourse / Glass navigation', icon: 'Menu', defaultProps: { paddingTop: 0, paddingBottom: 0, brand: 'CONCOURSE', announcement: 'A new chapter for finance — explore the platform', sticky: true, links: [{ label: 'Platform', url: '/platform' }, { label: 'Solutions', url: '/solutions' }, { label: 'Security', url: '/security' }, { label: 'Customers', url: '/customers' }, { label: 'Company', url: '/company' }], buttonLabel: 'Talk to our team', buttonUrl: '/company#contact' }, schema: schema(text('brand', 'Wordmark'), ...logoImageFields, text('announcement', 'Announcement'), navLinksField(), ...cta, stickyField), component: Nav }),
  defineBlock({ type: 'hero.concourse', version: 1, category: 'hero', label: 'Concourse / Cinematic hero', icon: 'Play', defaultProps: { ...base, paddingTop: 180, paddingBottom: 100, heading: 'Get ahead.\nStay ahead.', description: 'A new operating rhythm for enterprise finance.', eyebrow: '', image: asset('header-desktop-poster.webp'), video: asset('header-desktop.mp4'), buttonLabel: 'Talk to our team', buttonUrl: '/company#contact', layout: 'cinematic', animation: 'fade', animationTrigger: 'load' }, schema: schema(...headFields, ...cta, image('image', 'Poster image'), text('video', 'Background video URL'), select('layout', 'Hero style', ['cinematic', 'plain'])), component: Hero }),
  defineBlock({ type: 'logos.concourse', version: 1, category: 'content', label: 'Concourse / Moving logo strip', icon: 'Move', defaultProps: { paddingTop: 35, paddingBottom: 35, heading: 'Connected to the tools your team knows', moving: true, items: [{ title: 'Excel' }, { title: 'Slack' }, { title: 'Salesforce' }, { title: 'NetSuite' }, { title: 'Microsoft Teams' }, { title: 'Snowflake' }] }, schema: schema(text('heading', 'Caption'), toggle('moving', 'Animate logo strip'), repeater('items', 'Logos', [text('title', 'Name'), image('image', 'Logo')])), component: p => <SectionShell props={p} tone="primary" className="cq cq-logos"><EditableText edit={editOf(p)} path={['heading']} value={str(p.heading)} as="h2" /><div className={`cq-marquee ${p.moving ? 'cq-marquee--moving' : ''}`}><div>{[0, 1].map(copy => <div className="cq-logo-group" key={copy} aria-hidden={copy === 1}>{items(p.items, []).map((item, i) => <span key={i}>{str(item.image) ? <img src={str(item.image)} alt={str(item.title)} /> : copy === 0 ? <EditableText edit={editOf(p)} path={['items', i, 'title']} value={str(item.title)} as="span" /> : str(item.title)}</span>)}</div>)}</div></div></SectionShell> }),
  defineBlock({ type: 'features.concourse', version: 1, category: 'features', label: 'Concourse / Image feature cards', icon: 'Grid', defaultProps: { ...base, eyebrow: 'The platform', heading: 'Finance, with more possibility.', layout: 'three', items: [{ title: 'Built around your business.', description: 'Connect your systems and shape workflows around the way your team operates.', image: asset('showcase-feature-card-1.webp') }, { title: 'Clarity at every step.', description: 'Bring the evidence behind each result into view, from the original source to the final report.', image: asset('showcase-feature-card-2.webp') }, { title: 'Work in familiar places.', description: 'Deliver useful answers into the tools and conversations where decisions happen.', image: asset('showcase-feature-background-card-3.webp') }] }, schema: schema(...headFields, select('layout', 'Columns', ['two', 'three']), repeater('items', 'Features', cardFields)), component: Cards }),
  defineBlock({ type: 'statement.concourse', version: 1, category: 'content', label: 'Concourse / Architectural statement', icon: 'Layers', defaultProps: { ...base, eyebrow: 'People and technology, together', heading: 'Make the next move\nyour best move.', description: 'Bring your finance expertise together with a dedicated team that helps you turn ambitious ideas into everyday workflows.', buttonLabel: 'Meet the team', buttonUrl: '/company' }, schema: schema(...headFields, ...cta), component: p => <SectionShell props={p} tone="primary" className="cq cq-statement"><div className="cq-architecture" aria-hidden="true"><i /><i /><i /><i /><i /></div><div className="cq-statement-copy"><Head p={p} /><Cta p={p} /></div></SectionShell> }),
  defineBlock({ type: 'agents.concourse', version: 1, category: 'features', label: 'Concourse / Interactive agent showcase', icon: 'Activity', defaultProps: { ...base, eyebrow: 'From insight to action', heading: 'Give the work a new workflow.', items: agents }, schema: schema(...headFields, repeater('items', 'Agents', [text('title', 'Name'), textarea('description', 'Description'), text('result', 'Report title'), text('value', 'Highlight'), text('metric', 'Highlight label')])), component: Agents }),
  defineBlock({ type: 'testimonials.concourse', version: 1, category: 'testimonials', label: 'Concourse / Customer carousel', icon: 'Quote', defaultProps: { ...base, eyebrow: 'Customer perspectives', heading: 'Make room for bigger thinking.', items: [{ company: 'Example customer · Replace with your story', quote: 'The most valuable change is the time our team now has to ask better questions.', name: 'Alex Morgan', role: 'Finance leader · Sample testimonial' }, { company: 'Example customer · Replace with your story', quote: 'A connected workflow means we can spend more time on the decision and less time assembling the report.', name: 'Jordan Lee', role: 'Operations leader · Sample testimonial' }] }, schema: schema(...headFields, repeater('items', 'Testimonials', [text('company', 'Company'), textarea('quote', 'Quote'), text('name', 'Name'), text('role', 'Role')])), component: Quotes }),
  defineBlock({ type: 'solutions.concourse', version: 1, category: 'services', label: 'Concourse / Department grid', icon: 'Grid', defaultProps: { ...base, eyebrow: 'Across your organization', heading: 'One platform.\nEvery finance team.', layout: 'two', items: [{ title: 'Treasury', description: 'See your cash position, plan liquidity, and understand exposure across entities.', url: '/solutions#workflows' }, { title: 'Strategic finance', description: 'Explore scenarios, investigate performance, and build a plan with confidence.', url: '/solutions#workflows' }, { title: 'Accounting', description: 'Coordinate reconciliations and keep the close moving with connected evidence.', url: '/solutions#workflows' }, { title: 'Internal audit', description: 'Surface exceptions and organize the supporting context for review.', url: '/solutions#workflows' }] }, schema: schema(...headFields, select('layout', 'Columns', ['two', 'three']), repeater('items', 'Departments', cardFields)), component: Cards }),
  defineBlock({ type: 'integrations.concourse', version: 1, category: 'features', label: 'Concourse / Connected platform panels', icon: 'Link', defaultProps: { ...base, eyebrow: 'A connected foundation', heading: 'Your systems.\nWorking together.', layout: 'three', items: [{ title: 'Connect your data.', description: 'Bring the information your team needs into a shared, governed workflow.', image: asset('data-card-background.webp') }, { title: 'Keep your tools.', description: 'Deliver reports and updates into the applications people already use.', image: asset('data-card-background.webp') }, { title: 'Shape your platform.', description: 'Build an operating model around your team’s priorities and review process.', image: asset('data-card-background.webp') }] }, schema: schema(...headFields, select('layout', 'Columns', ['two', 'three']), repeater('items', 'Panels', cardFields)), component: Cards }),
  defineBlock({ type: 'stats.concourse', version: 1, category: 'content', label: 'Concourse / Impact metrics', icon: 'BarChart', defaultProps: { ...base, eyebrow: 'Track the difference', heading: 'Measure what moves you forward.', description: 'Illustrative metrics — replace with your verified results.', items: [{ value: '1,000+', label: 'Workflows connected' }, { value: '86%', label: 'Reduction in routine steps' }, { value: '20+', label: 'Hours returned each month' }, { value: '24/7', label: 'Operational visibility' }] }, schema: schema(...headFields, repeater('items', 'Metrics', [text('value', 'Value'), text('label', 'Label')])), component: p => <SectionShell props={p} className="cq cq-stats"><Head p={p} /><div className="cq-stat-grid">{items(p.items, []).map((item, i) => <div key={i}><EditableText edit={editOf(p)} path={['items', i, 'value']} value={str(item.value)} as="strong" /><EditableText edit={editOf(p)} path={['items', i, 'label']} value={str(item.label)} as="p" /></div>)}</div></SectionShell> }),
  defineBlock({ type: 'security.concourse', version: 1, category: 'features', label: 'Concourse / Security controls', icon: 'Shield', defaultProps: { ...base, eyebrow: 'Security and oversight', heading: 'Confidence is part\nof the architecture.', description: 'Define your access policies, keep evidence close, and put people in control of important decisions.', buttonLabel: 'Explore security', buttonUrl: '/security', items: [{ title: 'Access policies' }, { title: 'Identity controls' }, { title: 'Review workflows' }, { title: 'Data governance' }, { title: 'Model evaluations' }, { title: 'Activity history' }] }, schema: schema(...headFields, ...cta, repeater('items', 'Controls', [text('title', 'Control label')])), component: p => <SectionShell props={p} className="cq"><div className="cq-security"><div><Head p={p} /><Cta p={p} /></div><div className="cq-security-grid">{items(p.items, []).map((item, i) => <div key={i}><span aria-hidden="true">{['◇', '⊞', '◈', '⌘', '◎', '▤'][i % 6]}</span><EditableText edit={editOf(p)} path={['items', i, 'title']} value={str(item.title)} as="p" /></div>)}</div></div></SectionShell> }),
  defineBlock({ type: 'cta.concourse', version: 1, category: 'cta', label: 'Concourse / Closing invitation', icon: 'ArrowRight', defaultProps: { ...base, heading: 'Your next chapter\nstarts here.', buttonLabel: 'Talk to our team', buttonUrl: '/company#contact', eyebrow: '', description: '' }, schema: schema(...headFields, ...cta), component: p => <SectionShell props={p} tone="primary" className="cq cq-closing"><Head p={p} /><Cta p={p} /></SectionShell> }),
  defineBlock({ type: 'footer.concourse', version: 1, category: 'footer', label: 'Concourse / Editorial footer', icon: 'Layout', defaultProps: { paddingTop: 70, paddingBottom: 30, brand: 'CONCOURSE', description: 'A clearer way forward for finance.', copyright: '© 2026 Your company. All rights reserved.', links: [{ label: 'Platform', url: '/platform' }, { label: 'Solutions', url: '/solutions' }, { label: 'Security', url: '/security' }, { label: 'Customers', url: '/customers' }, { label: 'Company', url: '/company' }, { label: 'Contact', url: '/company#contact' }] }, schema: schema(text('brand', 'Wordmark'), ...logoImageFields, textarea('description', 'Description'), navLinksField(), text('copyright', 'Copyright')), component: p => <SectionShell props={p} tone="primary" className="cq cq-footer"><div className="cq-footer-top"><div><a className="cq-wordmark" href="/"><BrandLogo props={p} alt={str(p.brand)}>{str(p.brand)} ↗</BrandLogo></a><SafeText value={p.description} edit={editOf(p)} path={['description']} /></div><nav aria-label="Footer navigation">{items(p.links, []).map((item, i) => <a href={str(item.url)} key={i}>{str(item.label)} ↗</a>)}</nav></div><div className="cq-footer-bottom">{str(p.copyright)}<a href="/company#contact">Get in touch ↗</a></div></SectionShell> }),
]
