import { useEffect, useId, useRef, useState, type ReactNode } from 'react'
import type { BlockCategory, BlockField } from '@uidesired/types'
import { EditableText, editOf, useElementStyle, type EditPath } from '../editable'
import { Icon } from '../icons'
import { BrandLogo, Column, Media, SafeText, SectionShell, bool, cx, items, lines, num, str, type Props } from '../primitives'
import { PublicForm } from '../public-form'
import { columnStyleFields, headFields, icon, image, link, logoImageFields, navLinksField, number, repeater, schema, select, stickyField, text, textarea, toggle } from '../schema'
import { defineBlock, type BlockDefinition } from '../types'

const asset = (name: string) => `/template-assets/pawberry/${name}`
const base = { paddingTop: 85, paddingBottom: 85, animation: 'fade-up', animationDuration: 650, animationTrigger: 'scroll' }
const cta = [text('buttonLabel', 'Button label', { styleTarget: 'button' }), link('buttonUrl', 'Button link')]
const cardFields = [text('title', 'Title'), textarea('description', 'Description'), image('image', 'Image'), text('imageAlt', 'Image description')]
function define(type: string, category: BlockCategory, label: string, props: Props, fields: BlockField[], component: BlockDefinition['component']) {
  return defineBlock({ type: `${type}.pawberry`, category, version: 1, label: `Pawberry / ${label}`, icon: 'Heart', defaultProps: { ...base, ...props }, schema: schema(...fields), component })
}
function Head({ p, hero = false }: { p: Props; hero?: boolean }) { return <header className="pb-head">
  {str(p.eyebrow) && <EditableText edit={editOf(p)} path={['eyebrow']} value={str(p.eyebrow)} as="p" className="pb-eyebrow" />}
  <EditableText edit={editOf(p)} path={['heading']} value={str(p.heading)} as={hero ? 'h1' : 'h2'} className="pb-heading" />
  {str(p.description) && <SafeText value={p.description} edit={editOf(p)} path={['description']} className="pb-description" />}
</header> }
function Button({ p, item, path = [], className = '' }: { p: Props; item?: Props; path?: EditPath; className?: string }) {
  const source = item || p
  const style = useElementStyle([...path, 'buttonLabel', '$box'])
  return str(source.buttonLabel) ? <a href={str(source.buttonUrl, '/contact')} style={style} className={`pb-button ${className}`}><EditableText edit={editOf(p)} path={[...path, 'buttonLabel']} value={str(source.buttonLabel)} as="span" /></a> : null
}
function Doodle({ className = '' }: { className?: string }) { return <span aria-hidden="true" className={`pb-doodle ${className}`}><i /><i /><i /></span> }
function Paw() { return <svg className="pb-paw" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><ellipse cx="7" cy="11" rx="4" ry="5" transform="rotate(-25 7 11)" /><ellipse cx="14" cy="7" rx="4" ry="5" /><ellipse cx="23" cy="9" rx="4" ry="5" transform="rotate(20 23 9)" /><ellipse cx="28" cy="17" rx="3" ry="4" transform="rotate(30 28 17)" /><path d="M7 24c0-5 5-11 10-11s10 6 10 11c0 8-8 2-10 2S7 32 7 24Z" /></svg> }
function Picture({ p, item, index, ratio = 'portrait', styleKey }: { p: Props; item?: Props; index?: number; ratio?: string; styleKey?: string }) {
  const source = item || p
  return <Media src={source.image} alt={str(source.imageAlt, str(source.title))} ratio={ratio} styleKey={styleKey} edit={editOf(p)} path={item && index !== undefined ? ['items', index, 'image'] : ['image']} />
}
function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) {
  const ref = useRef<HTMLDialogElement>(null)
  const titleId = useId()
  useEffect(() => { const focused = document.activeElement as HTMLElement | null; ref.current?.showModal(); return () => { focused?.focus() } }, [])
  return <dialog ref={ref} className="pb-dialog" aria-labelledby={titleId} onCancel={onClose} onClick={event => { if (event.target === event.currentTarget) onClose() }}><div className="pb-dialog-panel"><button className="pb-dialog-close" type="button" onClick={onClose} aria-label="Close details">×</button><h2 id={titleId}>{title}</h2>{children}</div></dialog>
}
function Navigation(p: Props) {
  const [open, setOpen] = useState(false)
  const id = useId()
  return <SectionShell props={p} tone="surface" className={cx('pb', 'pb-nav-section', bool(p.sticky, true) && 'pb-nav-section--sticky')} bleed><div className="pb-nav"><a className="pb-brand" href={str(p.logoUrl, '/')}><BrandLogo props={p} alt={str(p.brand)}><Paw /><EditableText edit={editOf(p)} path={['brand']} value={str(p.brand)} as="span" /></BrandLogo></a><button type="button" className="pb-menu" aria-expanded={open} aria-controls={id} onClick={() => setOpen(!open)}>{open ? 'Close ×' : 'Menu ☰'}</button><nav id={id} aria-label="Main navigation" className={`pb-links ${open ? 'is-open' : ''}`}>{items(p.links, []).map((item, i) => <a href={str(item.url)} key={i} onClick={() => setOpen(false)}><EditableText edit={editOf(p)} path={['links', i, 'label']} value={str(item.label)} as="span" /></a>)}</nav><div className="pb-nav-action"><Button p={p} /></div></div></SectionShell>
}
function Hero(p: Props) { return <SectionShell props={p} className="pb pb-hero"><div className={`pb-hero-grid ${str(p.layout) === 'reverse' ? 'pb-reverse' : ''}`}><Column name="copyColumn"><Head p={p} hero /><Button p={p} /></Column><Column name="mediaColumn" className="pb-hero-art"><Picture p={p} ratio="1 / 1" /></Column></div></SectionShell> }
const team = [
  { title: 'Emma Brooks', role: 'Founder & groomer', description: 'A thoughtful approach, a patient pair of hands, and a soft spot for every pet who comes through the door.', image: asset('team-1.jpg'), imageAlt: 'A groomer with a golden dog' },
  { title: 'Noah Ellis', role: 'Grooming specialist', description: 'Noah takes time to understand each pet’s routine and helps every visit feel a little more familiar.', image: asset('team-2.jpg'), imageAlt: 'A pet-care specialist with a dog' },
  { title: 'Maya Chen', role: 'Cat-care specialist', description: 'Maya brings a gentle, unrushed approach to feline grooming and coat care.', image: asset('team-3.jpg'), imageAlt: 'A pet-care specialist holding a cat' },
  { title: 'Leo Martin', role: 'Bath & brush specialist', description: 'Leo enjoys the small details that make a fresh coat feel comfortable and easy to care for.', image: asset('team-4.jpg'), imageAlt: 'A member of the pet-care team' },
  { title: 'Sofia Reed', role: 'Pet stylist', description: 'Sofia works with owners to find a practical, comfortable finish suited to each pet’s coat.', image: asset('team-5.jpg'), imageAlt: 'A pet stylist with a dog' },
]
function Team(p: Props) {
  const [selected, setSelected] = useState<number | null>(null)
  const [paused, setPaused] = useState(false)
  const entries = items(p.items, [])
  const current = selected === null ? null : entries[selected]
  const strip = str(p.layout, 'strip') === 'strip'
  return <SectionShell props={p} className={`pb pb-team ${strip ? 'pb-team--strip' : ''}`} bleed={strip}>
    <div className={strip ? 'ud-container' : ''}><Head p={p} /><Button p={p} /></div>
    <div className={`pb-team-window ${strip ? 'pb-team-window--strip' : ''}`}><div className={`pb-team-track ${strip && bool(p.animate, true) && !paused ? 'is-moving' : ''}`}>
      {(strip ? [0, 1] : [0]).map(copy => <div className="pb-team-group" key={copy} aria-hidden={copy === 1}>{entries.map((item, i) => <article key={i}><Picture p={copy === 0 ? p : {}} item={item} index={i} /><button type="button" className="pb-team-caption" tabIndex={copy === 1 ? -1 : undefined} onClick={() => setSelected(i)}><strong>{str(item.title)}</strong><span>{str(item.role)} ↗</span></button></article>)}</div>)}
    </div></div>{strip && bool(p.animate, true) && <button type="button" className="pb-motion-button" onClick={() => setPaused(!paused)}>{paused ? 'Play photo strip' : 'Pause photo strip'}</button>}
    {current && <Dialog title={str(current.title)} onClose={() => setSelected(null)}><img src={str(current.image)} alt={str(current.imageAlt)} className="pb-profile-image" /><p className="pb-detail-meta">{str(current.role)}</p><p>{str(current.description)}</p><Button p={{ buttonLabel: str(p.detailLabel, 'Meet us at your next visit'), buttonUrl: str(p.detailUrl, '/contact') }} /></Dialog>}
  </SectionShell>
}
function Story(p: Props) { return <SectionShell props={p} className="pb pb-story"><div className={`pb-story-grid ${bool(p.reverse) ? 'pb-reverse' : ''}`}><Column name="copyColumn"><Head p={p} /><ul className="pb-checks">{items(p.items, []).map((item, i) => <li key={i}><Icon name={str(item.icon, 'check')} size={18} /><EditableText edit={editOf(p)} path={['items', i, 'text']} value={str(item.text)} as="span" /></li>)}</ul><Button p={p} /></Column><Column name="mediaColumn" className="pb-story-art"><Doodle /><Picture p={p} /><span className="pb-photo-corner" aria-hidden="true" /></Column></div></SectionShell> }
const services = [
  { title: 'Full grooming', category: 'Dogs', icon: 'heart', description: 'A fresh start from nose to tail, with a bath, careful brushing, and a coat trim tailored to your pet.', details: 'We begin with a conversation about your pet’s coat, routine, and comfort. The appointment includes a bath, drying, brushing, nail care, and a practical trim agreed with you.', duration: 'Allow 90–150 minutes', image: asset('team-1.jpg'), imageAlt: 'A dog enjoying gentle attention' },
  { title: 'Bath & brush', category: 'Dogs', icon: 'droplets', description: 'A gentle wash and a thorough brush to leave your companion feeling clean and comfortable.', details: 'A wash with coat-appropriate products, careful drying, and brushing to remove loose hair. We will discuss any tangles or additional work with you before getting started.', duration: 'Allow 45–90 minutes', image: asset('team-2.jpg'), imageAlt: 'A groomer and a relaxed dog' },
  { title: 'Nail care', category: 'All pets', icon: 'scissors', description: 'A short, unrushed appointment for tidy paws and a more comfortable everyday routine.', details: 'A gentle nail-care visit with time to help your pet settle. Let us know about previous experiences so we can plan an approach that suits them.', duration: 'Allow 15–30 minutes', image: asset('team-5.jpg'), imageAlt: 'A dog with a pet-care specialist' },
  { title: 'Gentle cat grooming', category: 'Cats', icon: 'sparkles', description: 'An individual approach to brushing and coat care for your feline companion.', details: 'We discuss your cat’s coat and temperament before arranging a suitable session. Our priority is a calm experience, with breaks and an approach tailored to your cat.', duration: 'Time agreed during consultation', image: asset('team-3.jpg'), imageAlt: 'A cat held by a pet-care specialist' },
]
function Services(p: Props) {
  const [filter, setFilter] = useState('All')
  const [selected, setSelected] = useState<number | null>(null)
  const entries = items(p.items, [])
  const filters = ['All', ...new Set(entries.map(item => str(item.category)).filter(Boolean))]
  const activeFilter = filters.includes(filter) ? filter : 'All'
  const current = selected === null ? null : entries[selected]
  return <SectionShell props={p} className="pb pb-services"><Doodle /><Head p={p} />{bool(p.showFilters) && <div className="pb-filters" aria-label="Filter services">{filters.map(value => <button type="button" key={value} aria-pressed={activeFilter === value} onClick={() => setFilter(value)}>{value}</button>)}</div>}
    <div className={`pb-service-grid pb-service-grid--${str(p.layout, 'cards')}`}>{entries.map((item, i) => (!bool(p.showFilters) || activeFilter === 'All' || str(item.category) === activeFilter) && <article key={i} className={`pb-service pb-color-${i % 3}`}>{str(p.layout) === 'image-cards' && <Picture p={p} item={item} index={i} ratio="landscape" />}<div className="pb-service-body"><span className="pb-service-icon"><Icon name={str(item.icon, 'heart')} size={28} /></span><EditableText edit={editOf(p)} path={['items', i, 'title']} value={str(item.title)} as="h3" /><SafeText value={item.description} edit={editOf(p)} path={['items', i, 'description']} /><button type="button" className="pb-read-more" onClick={() => setSelected(i)}>{str(p.readMoreLabel, 'Read more')} <span aria-hidden="true">↗</span></button></div></article>)}</div><div className="pb-centered-action"><Button p={p} /></div>
    {current && <Dialog title={str(current.title)} onClose={() => setSelected(null)}><img className="pb-dialog-image" src={str(current.image)} alt={str(current.imageAlt, str(current.title))} /><p className="pb-detail-meta">{str(current.duration)}</p><p>{str(current.details, str(current.description))}</p><Button p={{ buttonLabel: str(p.detailLabel, 'Ask about this service'), buttonUrl: str(p.detailUrl, '/contact') }} /></Dialog>}
  </SectionShell>
}
function Testimonials(p: Props) {
  const [active, setActive] = useState(0)
  const entries = items(p.items, [])
  const index = Math.min(active, Math.max(0, entries.length - 1))
  const current = entries[index]
  return <SectionShell props={p} className="pb pb-testimonials"><Head p={p} />{current && <div className="pb-testimonial" key={index}><Picture p={p} item={current} index={index} styleKey="mediaColumn" /><Column name="copyColumn" className="pb-testimonial-copy"><blockquote><EditableText edit={editOf(p)} path={['items', index, 'quote']} value={str(current.quote)} as="p" /></blockquote><EditableText edit={editOf(p)} path={['items', index, 'name']} value={str(current.name)} as="strong" /><EditableText edit={editOf(p)} path={['items', index, 'role']} value={str(current.role)} as="p" /><div className="pb-slider-controls"><button type="button" aria-label="Previous testimonial" onClick={() => setActive((index - 1 + entries.length) % entries.length)}>←</button><span>{index + 1} / {entries.length}</span><button type="button" aria-label="Next testimonial" onClick={() => setActive((index + 1) % entries.length)}>→</button></div></Column></div>}</SectionShell>
}
function price(value: unknown, currency: string) {
  try { return new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(num(value, 0)) }
  catch { return `${currency} ${num(value, 0)}` }
}
function Pricing(p: Props) {
  const [compare, setCompare] = useState(false)
  const entries = items(p.items, [])
  const comparisonId = useId()
  const currency = str(p.currency, 'USD')
  const features = [...new Set(entries.flatMap(item => lines(item.features)))]
  return <SectionShell props={p} className="pb pb-pricing"><Head p={p} /><Doodle /><div className="pb-pricing-grid">{entries.map((item, i) => <article className={`pb-price-card pb-color-${i % 3}`} key={i}><span className="pb-price">{str(p.pricePrefix, 'From')} {price(item.price, currency)}</span><EditableText edit={editOf(p)} path={['items', i, 'title']} value={str(item.title)} as="h3" /><SafeText value={item.description} edit={editOf(p)} path={['items', i, 'description']} /><ul>{lines(item.features).map((feature, j) => <li key={j}><span aria-hidden="true">✓</span>{feature}</li>)}</ul><Button p={p} item={item} path={['items', i]} /></article>)}</div><div className="pb-pricing-note"><SafeText value={p.note} edit={editOf(p)} path={['note']} /><button type="button" className="pb-read-more" aria-expanded={compare} aria-controls={comparisonId} onClick={() => setCompare(!compare)}>{compare ? str(p.hideCompareLabel, 'Hide comparison') : str(p.compareLabel, 'Compare plans')} {compare ? '−' : '+'}</button></div>{compare && <div id={comparisonId} className="pb-comparison"><table><caption>{str(p.comparisonTitle, 'What each package includes')}</caption><thead><tr><th scope="col">Included care</th>{entries.map((item, i) => <th scope="col" key={i}>{str(item.title)}</th>)}</tr></thead><tbody>{features.map(feature => <tr key={feature}><th scope="row">{feature}</th>{entries.map((item, i) => <td key={i}>{lines(item.features).includes(feature) ? 'Included' : '—'}</td>)}</tr>)}</tbody></table></div>}</SectionShell>
}
function VideoCta(p: Props) {
  const [paused, setPaused] = useState(false)
  const [reduced, setReduced] = useState(false)
  // Guarded because the block also renders where matchMedia does not exist -
  // server rendering and the test environment both reach this effect.
  useEffect(() => { if (typeof matchMedia !== 'function') return; const query = matchMedia('(prefers-reduced-motion: reduce)'); const sync = () => setReduced(query.matches); sync(); query.addEventListener('change', sync); return () => query.removeEventListener('change', sync) }, [])
  return <SectionShell props={p} className="pb pb-video-cta" bleed><img className="pb-video-bg" src={str(p.image)} alt={str(p.imageAlt)} />{str(p.videoUrl) && !editOf(p) && !paused && !reduced && <video className="pb-video-bg" src={str(p.videoUrl)} poster={str(p.image)} muted autoPlay loop playsInline aria-hidden="true" />}<div className="pb-video-shade" /><div className="ud-container"><Head p={p} /><Button p={p} /></div>{str(p.videoUrl) && !reduced && <button type="button" className="pb-video-toggle" onClick={() => setPaused(!paused)}>{paused ? 'Play video' : 'Pause video'}</button>}</SectionShell>
}
const articles = [
  { title: 'Making their first visit feel familiar', category: 'First visits', date: 'September 2026', description: 'A few small preparations for a calmer introduction to the grooming studio.', body: 'Start with a conversation. Let your groomer know what your pet enjoys, what worries them, and how previous visits have gone.\n\nKeep the journey unhurried and bring a familiar item if the studio recommends it. A short introduction can help some pets get to know the space before a longer appointment.\n\nEvery pet has a different pace. Agree on a realistic plan with your groomer and keep sharing what you notice at home.', image: asset('journal-1.jpg'), imageAlt: 'A person spending time with a kitten' },
  { title: 'A comfortable corner for your companion', category: 'Everyday care', date: 'September 2026', description: 'Thoughtful ideas for a quiet place to relax between everyday adventures.', body: 'Look for a comfortable spot away from busy walkways where your pet can choose to rest. Familiar bedding and a predictable daily rhythm can make the space feel welcoming.\n\nKeep water accessible and give your companion the choice to join the household or take some quiet time.\n\nNotice what your pet prefers and adjust the space around their habits. A favorite sunny corner might be just right.', image: asset('journal-2.jpg'), imageAlt: 'A person relaxing at home with a pet' },
  { title: 'Little adventures, happy afternoons', category: 'Life together', date: 'September 2026', description: 'Make time for simple outdoor moments and a change of scenery together.', body: 'A familiar walk can become a fresh adventure when there is time to explore. Choose an outing suited to your companion’s usual activity level and the weather.\n\nBring the everyday essentials and give your pet time to pause. A gentle change of route can add interest without making the day complicated.\n\nFor individual questions about exercise or health, ask your veterinarian. Your pet’s comfort comes first.', image: asset('journal-3.jpg'), imageAlt: 'A dog enjoying time outdoors with its owner' },
]
function Journal(p: Props) {
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<number | null>(null)
  const entries = items(p.items, [])
  const current = selected === null ? null : entries[selected]
  const visible = entries.map((item, index) => ({ item, index })).filter(({ item }) => !bool(p.showSearch) || `${str(item.title)} ${str(item.category)}`.toLowerCase().includes(query.toLowerCase()))
  return <SectionShell props={p} className="pb pb-journal"><div className="pb-heading-row"><Head p={p} /><Button p={p} /></div>{bool(p.showSearch) && <label className="pb-search"><span>{str(p.searchLabel, 'Find a story')}</span><input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder={str(p.searchPlaceholder, 'Search pet-care stories')} /></label>}<div className="pb-journal-grid">{visible.map(({ item, index }) => <article key={index}><Picture p={p} item={item} index={index} ratio="landscape" /><button type="button" className="pb-journal-title" onClick={() => setSelected(index)}><h3>{str(item.title)}</h3></button><EditableText edit={editOf(p)} path={['items', index, 'date']} value={str(item.date)} as="p" className="pb-article-date" /></article>)}</div>{!visible.length && <p role="status">{str(p.emptyLabel, 'No stories match your search.')}</p>}{current && <Dialog title={str(current.title)} onClose={() => setSelected(null)}><img className="pb-dialog-image" src={str(current.image)} alt={str(current.imageAlt)} /><p className="pb-detail-meta">{str(current.category)} · {str(current.date)}</p><div className="pb-article-body">{lines(str(current.body).replace(/\n\n/g, '\n')).map((paragraph, i) => <p key={i}>{paragraph}</p>)}</div><Button p={{ buttonLabel: str(p.detailLabel, 'Talk to our team'), buttonUrl: str(p.detailUrl, '/contact') }} /></Dialog>}</SectionShell>
}
function Faq(p: Props) { return <SectionShell props={p} className="pb pb-faq"><div className="pb-faq-grid"><Column name="copyColumn"><Head p={p} /><Button p={p} /></Column><Column name="mediaColumn">{items(p.items, []).map((item, i) => <details key={i}><summary><EditableText edit={editOf(p)} path={['items', i, 'question']} value={str(item.question)} as="span" /><span aria-hidden="true">+</span></summary><SafeText value={item.answer} edit={editOf(p)} path={['items', i, 'answer']} /></details>)}</Column></div></SectionShell> }
function Contact(p: Props) { return <SectionShell props={p} className="pb pb-contact"><div className="pb-contact-grid"><Column name="copyColumn"><Head p={p} /><div className="pb-contact-details">{items(p.items, []).map((item, i) => <div key={i}><Icon name={str(item.icon, 'mail')} size={20} /><div><EditableText edit={editOf(p)} path={['items', i, 'title']} value={str(item.title)} as="strong" />{str(item.url) ? <a href={str(item.url)}>{str(item.value)}</a> : <EditableText edit={editOf(p)} path={['items', i, 'value']} value={str(item.value)} as="p" />}</div></div>)}</div><Doodle /></Column><Column name="mediaColumn" className="pb-form-card"><EditableText edit={editOf(p)} path={['formHeading']} value={str(p.formHeading)} as="h3" /><PublicForm formId={str(p.formId) || undefined} submitLabel={str(p.buttonLabel)} edit={editOf(p)} submitLabelPath={['buttonLabel']} fields={[{ name: 'name', label: 'Your name', type: 'text', required: true }, { name: 'email', label: 'Email address', type: 'email', required: true }, { name: 'message', label: 'Tell us about your pet and preferred visit', type: 'textarea', required: true }]} /><SafeText value={p.note} edit={editOf(p)} path={['note']} className="pb-form-note" /></Column></div></SectionShell> }

export const pawberryBlocks = [
  define('navbar', 'navigation', 'Centered brand navigation', { paddingTop: 0, paddingBottom: 0, animation: 'none', tone: 'surface', sticky: true, brand: 'Pawberry', logoUrl: '/', buttonLabel: 'Book a visit', buttonUrl: '/contact', links: [{ label: 'Home', url: '/' }, { label: 'About', url: '/about' }, { label: 'Services', url: '/services' }, { label: 'Pricing', url: '/pricing' }, { label: 'Team', url: '/team' }, { label: 'Journal', url: '/journal' }] }, [text('brand', 'Brand name'), ...logoImageFields, link('logoUrl', 'Brand link'), navLinksField(), ...cta, stickyField], Navigation),
  define('hero', 'hero', 'Pet portrait hero', { paddingTop: 40, paddingBottom: 0, tone: 'surface', heading: 'A little pampering.\nA whole lot of love.', description: 'Thoughtful grooming and gentle care for your happiest, fluffiest companion.', image: asset('hero.webp'), imageAlt: 'A cheerful golden dog with playful colorful shapes', buttonLabel: 'Book an appointment', buttonUrl: '/contact', layout: 'split', animation: 'fade', animationTrigger: 'load' }, [...headFields, image('image', 'Hero image'), text('imageAlt', 'Image description'), ...cta, select('layout', 'Composition', ['split', 'reverse']), ...columnStyleFields(['copyColumn', 'Copy column'], ['mediaColumn', 'Photo column'])], Hero),
  define('page_header', 'hero', 'Soft inner-page introduction', { tone: 'surface', eyebrow: 'Welcome to Pawberry', heading: 'Good care.\nHappy companions.', description: 'A friendly place for pets and the people who love them.' }, [...headFields], p => <SectionShell props={p} className="pb pb-page-header"><Doodle /><Head p={p} /><a className="pb-breadcrumb" href="/">Home ↗</a></SectionShell>),
  define('team', 'team', 'Moving portraits and team grid', { eyebrow: 'Our people', heading: 'Big hearts.\nA soft spot for pets.', description: 'Meet the friendly faces who make every visit feel a little more familiar.', buttonLabel: 'Meet our team', buttonUrl: '/team', detailLabel: 'Meet us at your next visit', detailUrl: '/contact', layout: 'strip', animate: true, items: team }, [...headFields, ...cta, select('layout', 'Portrait layout', ['strip', 'grid']), toggle('animate', 'Animate portrait strip'), text('detailLabel', 'Profile button label'), link('detailUrl', 'Profile button link'), repeater('items', 'Team members', [...cardFields, text('role', 'Role')])], Team),
  define('story', 'content', 'Story and rounded photograph', { tone: 'surface', eyebrow: 'Our story', heading: 'Your neighborhood\nhappy-pet people.', description: 'We make time for the little things: a reassuring hello, a familiar routine, and a finish that feels just right.', image: asset('story.webp'), imageAlt: 'An owner cuddling a golden dog', buttonLabel: 'A little about us', buttonUrl: '/about', reverse: false, items: [{ icon: 'users', text: 'A familiar, friendly team' }, { icon: 'shield-check', text: 'Comfort comes first' }, { icon: 'heart', text: 'Care tailored to your companion' }] }, [...headFields, image('image', 'Story photo'), text('imageAlt', 'Image description'), ...cta, toggle('reverse', 'Reverse columns'), repeater('items', 'Reassurance points', [icon('icon', 'Icon'), text('text', 'Text')]), ...columnStyleFields(['copyColumn', 'Copy column'], ['mediaColumn', 'Photo column'])], Story),
  define('services', 'services', 'Service cards and details', { eyebrow: 'Our services', heading: 'A fresh look for\nyour favorite buddy.', buttonLabel: 'See all services', buttonUrl: '/services', readMoreLabel: 'Read more', detailLabel: 'Ask about this service', detailUrl: '/contact', layout: 'cards', showFilters: false, items: services.slice(0, 3) }, [...headFields, ...cta, text('readMoreLabel', 'Card button label'), text('detailLabel', 'Detail button label'), link('detailUrl', 'Detail button link'), select('layout', 'Card layout', ['cards', 'image-cards']), toggle('showFilters', 'Show pet filters'), repeater('items', 'Services', [...cardFields, icon('icon', 'Icon'), text('category', 'Pet category'), textarea('details', 'Full details'), text('duration', 'Appointment duration')])], Services),
  define('testimonials', 'testimonials', 'Photo testimonial slider', { tone: 'surface', eyebrow: 'Kind words', heading: 'Happy pets.\nHappy people.', items: [{ image: asset('testimonial-1.webp'), imageAlt: 'An owner with a golden dog', quote: 'A warm welcome, a patient team, and a very happy companion on the way home. The little details make such a difference.', name: 'Jamie & Willow', role: 'Illustrative client story — replace with permission' }, { image: asset('testimonial-2.webp'), imageAlt: 'An owner spending time with a cat', quote: 'We appreciated the time to talk through our cat’s routine and find an approach that felt comfortable for everyone.', name: 'Alex & Milo', role: 'Illustrative client story — replace with permission' }] }, [...headFields, repeater('items', 'Testimonials', [image('image', 'Photo'), text('imageAlt', 'Image description'), textarea('quote', 'Quote'), text('name', 'Name'), text('role', 'Caption')]), ...columnStyleFields(['copyColumn', 'Quote column'], ['mediaColumn', 'Photo column'])], Testimonials),
  define('pricing', 'pricing', 'Packages with plan comparison', { eyebrow: 'Simple packages', heading: 'Find their kind\nof fresh.', currency: 'USD', pricePrefix: 'From', compareLabel: 'Compare plans', hideCompareLabel: 'Hide comparison', comparisonTitle: 'What each package includes', note: 'Example starting prices. Final service and price are confirmed with you before the appointment.', items: [{ title: 'Freshen up', price: 65, description: 'An everyday reset for a clean, comfortable coat.', features: 'Gentle bath\nCoat brushing\nEar cleaning\nNail care', buttonLabel: 'Ask about Freshen up', buttonUrl: '/contact' }, { title: 'The full fluff', price: 95, description: 'Our complete grooming visit, with a finish that suits your pet.', features: 'Gentle bath\nCoat brushing\nEar cleaning\nNail care\nCoat trim', buttonLabel: 'Ask about The full fluff', buttonUrl: '/contact' }, { title: 'Extra TLC', price: 125, description: 'A little more time for coats that need extra attention.', features: 'Gentle bath\nCoat brushing\nEar cleaning\nNail care\nCoat trim\nExtra coat-care time', buttonLabel: 'Ask about Extra TLC', buttonUrl: '/contact' }] }, [...headFields, select('currency', 'Currency', ['USD', 'EUR', 'GBP', 'AED', 'CAD', 'AUD'], 'content'), text('pricePrefix', 'Price prefix'), text('compareLabel', 'Comparison button label'), text('hideCompareLabel', 'Hide comparison label'), text('comparisonTitle', 'Comparison title'), textarea('note', 'Pricing note'), repeater('items', 'Packages', [text('title', 'Package'), number('price', 'Starting price', 'content', { min: 0 }), textarea('description', 'Description'), textarea('features', 'Included care (one per line)'), ...cta])], Pricing),
  define('video_cta', 'cta', 'Cinematic pet-care invitation', { paddingTop: 125, paddingBottom: 125, eyebrow: 'A little time, just for them', heading: 'Let’s look after\nyour best buddy.', image: asset('visit.jpg'), imageAlt: 'An owner relaxing outdoors with a dog', videoUrl: asset('visit.mp4'), buttonLabel: 'Plan a visit', buttonUrl: '/contact' }, [...headFields, image('image', 'Video poster'), text('imageAlt', 'Image description'), text('videoUrl', 'Background video URL'), ...cta], VideoCta),
  define('journal', 'blog', 'Searchable pet-care journal', { tone: 'surface', eyebrow: 'Notes from Pawberry', heading: 'A little more\nabout life with pets.', buttonLabel: 'All stories', buttonUrl: '/journal', showSearch: false, searchLabel: 'Find a story', searchPlaceholder: 'Search pet-care stories', emptyLabel: 'No stories match your search.', detailLabel: 'Talk to our team', detailUrl: '/contact', items: articles }, [...headFields, ...cta, toggle('showSearch', 'Show story search'), text('searchLabel', 'Search label'), text('searchPlaceholder', 'Search placeholder'), text('emptyLabel', 'Empty results text'), text('detailLabel', 'Article button label'), link('detailUrl', 'Article button link'), repeater('items', 'Articles', [...cardFields, text('category', 'Category'), text('date', 'Display date'), textarea('body', 'Article body')])], Journal),
  define('faq', 'faq', 'Friendly questions accordion', { eyebrow: 'Good questions', heading: 'You ask.\nWe’re all ears.', description: 'A little information to help you feel ready for your first visit.', buttonLabel: 'Ask us anything', buttonUrl: '/contact', items: [{ question: 'Do you care for cats as well as dogs?', answer: 'Yes. Contact the team to discuss your pet and the type of care you are looking for. We will help you find the right service.' }, { question: 'How long should we allow for a visit?', answer: 'It depends on your pet’s coat and the service. We will discuss timing when arranging the appointment and let you know when they are ready.' }, { question: 'Can we talk about a nervous pet first?', answer: 'Absolutely. Tell us about previous experiences and what helps your pet feel comfortable so we can plan together.' }, { question: 'How is the final price confirmed?', answer: 'The packages show example starting prices. We confirm the service, coat requirements, and final price with you before beginning.' }, { question: 'How do I request an appointment?', answer: 'Use the contact form to tell us about your pet and preferred visit. Our team will reply to confirm availability. Sending a request does not automatically reserve a time.' }] }, [...headFields, ...cta, repeater('items', 'Questions', [text('question', 'Question'), textarea('answer', 'Answer')]), ...columnStyleFields(['copyColumn', 'Intro column'], ['mediaColumn', 'Questions column'])], Faq),
  define('process', 'content', 'Visit journey cards', { tone: 'surface', eyebrow: 'Your first visit', heading: 'A friendly hello.\nA comfortable routine.', items: [{ title: 'Tell us about your pet', description: 'Share their coat, personality, and any preferences before we meet.' }, { title: 'Make a plan together', description: 'We agree on the care, timing, and price before the appointment begins.' }, { title: 'Head home feeling fresh', description: 'We share how the visit went and talk about the next steps in their routine.' }] }, [...headFields, repeater('items', 'Steps', [text('title', 'Title'), textarea('description', 'Description')])], p => <SectionShell props={p} className="pb pb-process"><Head p={p} /><div className="pb-process-grid">{items(p.items, []).map((item, i) => <article key={i}><span>{String(i + 1).padStart(2, '0')}</span><EditableText edit={editOf(p)} path={['items', i, 'title']} value={str(item.title)} as="h3" /><SafeText value={item.description} edit={editOf(p)} path={['items', i, 'description']} /></article>)}</div></SectionShell>),
  define('form', 'form', 'Connected booking inquiry', { eyebrow: 'Let’s meet your companion', heading: 'A fresh start\nbegins with hello.', description: 'Ask a question or request a visit. We will get back to you to confirm the details.', formId: '', formHeading: 'Request an appointment', buttonLabel: 'Send my inquiry', note: 'This is an appointment request. Your visit is confirmed when the team replies with an available time.', items: [{ icon: 'mail', title: 'Email', value: 'hello@pawberry.example', url: 'mailto:hello@pawberry.example' }, { icon: 'clock', title: 'Studio hours', value: 'Monday–Saturday · By appointment' }, { icon: 'map-pin', title: 'Come visit', value: 'Add your studio address in the builder' }] }, [...headFields, text('formId', 'Connected form'), text('formHeading', 'Form heading'), text('buttonLabel', 'Submit label'), textarea('note', 'Form note'), repeater('items', 'Contact details', [icon('icon', 'Icon'), text('title', 'Label'), text('value', 'Value'), link('url', 'Link')]), ...columnStyleFields(['copyColumn', 'Details column'], ['mediaColumn', 'Form column'])], Contact),
  define('footer', 'footer', 'Warm multipage footer', { paddingTop: 70, paddingBottom: 25, tone: 'surface', brand: 'Pawberry', tagline: 'Good care for your favorite companion.', copyright: '© 2026 Pawberry. All rights reserved.', buttonLabel: 'Book a visit', buttonUrl: '/contact', contactHeading: 'Let’s talk', email: 'hello@pawberry.example', emailUrl: 'mailto:hello@pawberry.example', location: 'Your neighborhood grooming studio', links: [{ label: 'Home', url: '/' }, { label: 'About', url: '/about' }, { label: 'Services', url: '/services' }, { label: 'Pricing', url: '/pricing' }, { label: 'Our team', url: '/team' }, { label: 'Journal', url: '/journal' }, { label: 'Contact', url: '/contact' }] }, [text('brand', 'Brand'), ...logoImageFields, textarea('tagline', 'Tagline'), text('copyright', 'Copyright'), ...cta, text('contactHeading', 'Contact heading'), text('email', 'Email label'), link('emailUrl', 'Email link'), text('location', 'Location'), navLinksField()], p => <SectionShell props={p} className="pb pb-footer"><div className="pb-footer-grid"><div><a href="/" className="pb-brand"><BrandLogo props={p} alt={str(p.brand)}><Paw /><EditableText edit={editOf(p)} path={['brand']} value={str(p.brand)} as="span" /></BrandLogo></a><SafeText value={p.tagline} edit={editOf(p)} path={['tagline']} /></div><nav aria-label="Footer navigation">{items(p.links, []).map((item, i) => <a href={str(item.url)} key={i}><EditableText edit={editOf(p)} path={['links', i, 'label']} value={str(item.label)} as="span" /></a>)}</nav><div className="pb-footer-contact"><EditableText edit={editOf(p)} path={['contactHeading']} value={str(p.contactHeading)} as="h3" /><a href={str(p.emailUrl)}>{str(p.email)}</a><EditableText edit={editOf(p)} path={['location']} value={str(p.location)} as="p" /><Button p={p} /></div></div><div className="pb-footer-bottom"><EditableText edit={editOf(p)} path={['copyright']} value={str(p.copyright)} as="span" /><Paw /></div></SectionShell>),
]

