import { useId, useState } from 'react'
import type { BlockCategory, BlockField } from '@uidesired/types'
import { EditableText, editOf, pathId, useElementStyle } from '../editable'
import { BrandLogo, Column, Media, SafeText, SectionShell, bool, items, str, type Props } from '../primitives'
import { PublicForm } from '../public-form'
import { columnStyleFields, headFields, image, link, logoImageFields, navLinksField, number, repeater, schema, select, stickyField, text, textarea, toggle } from '../schema'
import { defineBlock, type BlockDefinition } from '../types'

const asset = (name: string) => `/template-assets/veloura/${name}.avif`
const cta = [text('buttonLabel', 'Button label', { styleTarget: 'button' }), link('buttonUrl', 'Button link')]
const moneyFields = [text('pricePrefix', 'Price prefix'), select('currency', 'Currency symbol', ['$', '€', '£', 'AED'], 'content')]
const photoFields = [image('image', 'Photograph'), text('imageAlt', 'Image description')]
const columns = columnStyleFields(['copyColumn', 'Copy column'], ['mediaColumn', 'Media column'])
const links = ['Home', 'About', 'Services', 'Pricing', 'Gallery', 'Team', 'Contact'].map(label => ({ label, url: label === 'Home' ? '/' : `/${label.toLowerCase()}` }))
const dark = { backgroundColor: '#1d261b', textColor: '#fdfcfc', headingColor: '#fdfcfc' }
function define(type: string, category: BlockCategory, label: string, props: Props, fields: BlockField[], component: BlockDefinition['component']) {
  return defineBlock({ type: `${type}.veloura`, category, version: 1, label: `Veloura / ${label}`, icon: 'Scissors', defaultProps: { paddingTop: 88, paddingBottom: 88, backgroundType: props.backgroundColor ? 'color' : 'tone', headingFont: 'Inter, sans-serif', bodyFont: 'Inter, sans-serif', ...props }, schema: schema(...fields), component })
}
function Copy({ p, name, as = 'p' }: { p: Props; name: string; as?: 'p' | 'h1' | 'h2' | 'h3' | 'span' }) { return <EditableText edit={editOf(p)} path={[name]} value={str(p[name])} as={as} /> }
function Head({ p, hero = false }: { p: Props; hero?: boolean }) { return <header className="vl-head">{str(p.eyebrow) && <div className="vl-eyebrow"><Copy p={p} name="eyebrow" /></div>}<Copy p={p} name="heading" as={hero ? 'h1' : 'h2'} />{str(p.description) && <SafeText value={p.description} edit={editOf(p)} path={['description']} className="vl-lead" />}</header> }
function Button({ p }: { p: Props }) { const buttonPath = ['buttonLabel', '$box']; const style = useElementStyle(buttonPath); return str(p.buttonLabel) ? <a href={str(p.buttonUrl, '/appointment')} className="vl-button" style={style} data-ud-style={pathId(buttonPath)}><Copy p={p} name="buttonLabel" as="span" /><span aria-hidden="true">↗</span></a> : null }
function Photo({ p, row, index, ratio = 'portrait' }: { p: Props; row?: Props; index?: number; ratio?: string }) { const source = row || p; return <Media src={source.image} alt={str(source.imageAlt, str(source.title))} ratio={ratio} edit={editOf(p)} path={row && index !== undefined ? ['items', index, 'image'] : ['image']} /> }
function Price({ p, row }: { p: Props; row: Props }) { return <span>{str(p.pricePrefix, 'From')} {str(p.currency, '$')}{Number(row.price) || 0}</span> }
function RowText({ p, row, index, name, as = 'p' }: { p: Props; row: Props; index: number; name: string; as?: 'p' | 'h3' | 'span' }) { return <EditableText edit={editOf(p)} path={['items', index, name]} value={str(row[name])} as={as} /> }
function Nav(p: Props) { const [open, setOpen] = useState(false); const id = useId(); return <SectionShell props={p} className={`vl vl-nav ${bool(p.sticky, true) ? 'vl-sticky' : ''}`}><div className="vl-nav-inner"><a className="vl-brand" href={str(p.logoUrl, '/')}><BrandLogo props={p} alt={str(p.brand)}><Copy p={p} name="brand" as="span" /><span aria-hidden="true">✳</span></BrandLogo></a><button type="button" className="vl-menu" aria-expanded={open} aria-controls={id} onClick={() => setOpen(!open)}>{open ? 'Close ×' : 'Menu ☰'}</button><nav id={id} className={open ? 'is-open' : ''} aria-label="Main navigation">{items(p.links, []).map((row, i) => <a key={i} href={str(row.url)} onClick={() => setOpen(false)}><EditableText edit={editOf(p)} path={['links', i, 'label']} value={str(row.label)} as="span" /></a>)}</nav><div className="vl-nav-cta"><Button p={p} /></div></div></SectionShell> }
function Hero(p: Props) { return <SectionShell props={p} className="vl vl-hero" bleed><div className="vl-hero-grid"><Column name="copyColumn" className="vl-hero-copy"><Head p={p} hero /><Button p={p} /><div className="vl-hero-note"><span aria-hidden="true">✳</span><Copy p={p} name="note" /></div></Column><Column name="mediaColumn" className="vl-hero-photo"><Photo p={p} ratio="4 / 5" /><div className="vl-photo-caption"><Copy p={p} name="caption" as="span" /><span aria-hidden="true">✳</span></div></Column></div></SectionShell> }
function Story(p: Props) { return <SectionShell props={p} className="vl"><div className={`vl-split ${bool(p.reverse) ? 'vl-reverse' : ''}`}><Column name="copyColumn"><Head p={p} /><Button p={p} /></Column><Column name="mediaColumn" className="vl-story-photo"><Photo p={p} ratio="4 / 3" /></Column></div></SectionShell> }
const services = [
  { title: 'Cut & finish', description: 'A considered cut, shaped around your texture and everyday routine.', details: 'Start with a consultation, followed by a wash, precision cut and a finish that shows you how to wear it at home.', price: 65, image: asset('service-1'), imageAlt: 'Hair styling in the salon' },
  { title: 'Colour & dimension', description: 'From a subtle refresh to a brighter, bolder chapter.', details: 'Your colourist will discuss tone, upkeep and hair history, then confirm the treatment plan and quote before your appointment.', price: 120, image: asset('service-2'), imageAlt: 'Professional colour service' },
  { title: 'Care & repair', description: 'Give your hair a little time, attention and softness.', details: 'A consultation helps us choose conditioning care for your hair. Your stylist explains the treatment and an easy home-care routine.', price: 45, image: asset('service-3'), imageAlt: 'Personal hair care treatment' },
]
function Services(p: Props) { return <SectionShell props={p} className="vl"><Head p={p} /><div className="vl-cards">{items(p.items, []).map((row, i) => <article className="vl-service" key={i}><Photo p={p} row={row} index={i} ratio="4 / 3" /><div className="vl-card-body"><div className="vl-number">0{i + 1} / <Price p={p} row={row} /></div><RowText p={p} row={row} index={i} name="title" as="h3" /><RowText p={p} row={row} index={i} name="description" /><details><summary>{str(p.detailsLabel)} <span aria-hidden="true">+</span></summary><RowText p={p} row={row} index={i} name="details" /><Button p={p} /></details></div></article>)}</div></SectionShell> }
function Process(p: Props) { return <SectionShell props={p} className="vl vl-process"><Head p={p} /><div className="vl-cards">{items(p.items, []).map((row, i) => <article key={i}><span className="vl-step">0{i + 1}</span><RowText p={p} row={row} index={i} name="title" as="h3" /><RowText p={p} row={row} index={i} name="description" /></article>)}</div></SectionShell> }
function Gallery(p: Props) { const [filter, setFilter] = useState('All'); const entries = items(p.items, []); const filters = ['All', ...new Set(entries.map(row => str(row.category)).filter(Boolean))]; const active = filters.includes(filter) ? filter : 'All'; return <SectionShell props={p} className="vl"><Head p={p} />{bool(p.showFilters, true) && <div className="vl-filters" aria-label="Filter gallery">{filters.map(value => <button type="button" key={value} aria-pressed={active === value} onClick={() => setFilter(value)}>{value}</button>)}</div>}<div className="vl-gallery">{entries.map((row, i) => (!bool(p.showFilters, true) || active === 'All' || active === str(row.category)) && <figure key={i}><Photo p={p} row={row} index={i} /><figcaption><RowText p={p} row={row} index={i} name="title" as="span" /><RowText p={p} row={row} index={i} name="category" as="span" /></figcaption></figure>)}</div><Button p={p} /></SectionShell> }
function Team(p: Props) { return <SectionShell props={p} className="vl"><Head p={p} /><div className="vl-team">{items(p.items, []).map((row, i) => <article key={i}><Photo p={p} row={row} index={i} /><RowText p={p} row={row} index={i} name="title" as="h3" /><RowText p={p} row={row} index={i} name="role" /><details><summary>{str(p.detailsLabel)} +</summary><RowText p={p} row={row} index={i} name="description" /></details></article>)}</div></SectionShell> }
function Testimonials(p: Props) { const [active, setActive] = useState(0); const entries = items(p.items, []); const index = entries.length ? active % entries.length : 0; const row = entries[index]; return <SectionShell props={p} className="vl vl-testimonials"><div className="vl-split"><Head p={p} />{row && <div><div aria-live="polite"><span className="vl-stars" aria-label="Five stars">★★★★★</span><blockquote><RowText p={p} row={row} index={index} name="quote" /></blockquote><RowText p={p} row={row} index={index} name="name" /><RowText p={p} row={row} index={index} name="service" /></div><div className="vl-arrows"><button type="button" aria-label="Previous testimonial" onClick={() => setActive((index + entries.length - 1) % entries.length)}>←</button><span>{index + 1} / {entries.length}</span><button type="button" aria-label="Next testimonial" onClick={() => setActive((index + 1) % entries.length)}>→</button></div></div>}</div></SectionShell> }
function Pricing(p: Props) { return <SectionShell props={p} className="vl"><div className="vl-split"><div><Head p={p} /><Button p={p} /></div><div className="vl-price-list">{items(p.items, []).map((row, i) => <article key={i}><div><RowText p={p} row={row} index={i} name="title" as="h3" /><RowText p={p} row={row} index={i} name="description" /></div><Price p={p} row={row} /></article>)}</div></div></SectionShell> }
function Faq(p: Props) { return <SectionShell props={p} className="vl"><div className="vl-split"><Head p={p} /><div className="vl-faq">{items(p.items, []).map((row, i) => <details key={i} open={editOf(p) ? true : undefined}><summary><RowText p={p} row={row} index={i} name="question" as="span" /><span aria-hidden="true">+</span></summary><RowText p={p} row={row} index={i} name="answer" /></details>)}</div></div></SectionShell> }
function Contact(p: Props) { return <SectionShell props={p} className="vl"><div className="vl-split"><Column name="copyColumn"><Head p={p} /><div className="vl-contact-info">{items(p.items, []).map((row, i) => <div key={i}><RowText p={p} row={row} index={i} name="title" as="h3" />{str(row.url) ? <a href={str(row.url)}><RowText p={p} row={row} index={i} name="value" as="span" /></a> : <RowText p={p} row={row} index={i} name="value" />}</div>)}</div></Column><Column name="mediaColumn" className="vl-form"><Copy p={p} name="formHeading" as="h3" /><PublicForm formId={str(p.formId) || undefined} submitLabel={str(p.buttonLabel)} edit={editOf(p)} submitLabelPath={['buttonLabel']} fields={[{ name: 'name', label: 'Your name', type: 'text', required: true }, { name: 'email', label: 'Email address', type: 'email', required: true }, { name: 'message', label: 'Service and preferred appointment time', type: 'textarea', required: true }]} /><Copy p={p} name="note" /></Column></div></SectionShell> }
export const velouraBlocks = [
  define('navbar', 'navigation', 'Salon navigation', { ...dark, paddingTop: 22, paddingBottom: 22, brand: 'Veloura', logoUrl: '/', links, sticky: true, buttonLabel: 'Book a visit', buttonUrl: '/appointment' }, [text('brand', 'Brand'), ...logoImageFields, link('logoUrl', 'Logo link'), navLinksField(), stickyField, ...cta], Nav),
  define('hero', 'hero', 'Split portrait hero', { ...dark, paddingTop: 0, paddingBottom: 0, eyebrow: 'YOUR HAIR. YOUR EXPRESSION.', heading: 'Great hair.\nA little more you.', description: 'Personal cuts, thoughtful colour and a salon that makes space for you. Find your next look at Veloura.', buttonLabel: 'Find your next look', buttonUrl: '/services', image: asset('hero'), imageAlt: 'Stylist creating a fresh salon look', note: 'A fresh perspective, from the first consultation.', caption: 'GOOD HAIR STARTS HERE' }, [...headFields, ...cta, ...photoFields, text('note', 'Note'), text('caption', 'Photo caption'), ...columns], Hero),
  define('page_header', 'hero', 'Interior page introduction', { ...dark, eyebrow: 'VELOURA STUDIO', heading: 'A style that feels like you.', description: 'Thoughtful hair care, from first hello to the finishing touch.' }, [...headFields], p => <SectionShell props={p} className="vl vl-page-header"><Head p={p} hero /></SectionShell>),
  define('story', 'content', 'Editorial salon story', { eyebrow: 'A LITTLE ABOUT US', heading: 'Good conversations.\nEven better hair.', description: 'We start by listening. Your texture, your routine, the way you want to feel. Then we bring care and creativity to a look you can make your own.', image: asset('story'), imageAlt: 'Inside a welcoming hair salon', buttonLabel: 'Our story', buttonUrl: '/about', reverse: false }, [...headFields, ...photoFields, ...cta, toggle('reverse', 'Reverse columns'), ...columns], Story),
  define('services', 'services', 'Expandable service cards', { pricePrefix: 'From', currency: '$', eyebrow: 'THE SALON MENU', heading: 'A fresh take on your everyday.', description: 'Explore a little change, a complete transformation, or simply time for yourself.', items: services, detailsLabel: 'Explore service', buttonLabel: 'Request this service', buttonUrl: '/appointment' }, [...headFields, ...moneyFields, repeater('items', 'Services', [text('title', 'Service'), textarea('description', 'Summary'), textarea('details', 'Full details'), ...photoFields, number('price', 'Starting price', 'content')]), text('detailsLabel', 'Details label'), ...cta], Services),
  define('process', 'features', 'Three-step visit', { backgroundColor: '#f1c376', eyebrow: 'MAKE YOURSELF AT HOME', heading: 'Your next good hair day starts here.', items: [{ title: 'Tell us your vision', description: 'Share what you love, what you would change and what works for your routine.' }, { title: 'Make a plan together', description: 'We talk through the options, timing and price before your service begins.' }, { title: 'Leave feeling yourself', description: 'Enjoy the finishing touches and take away simple tips for styling at home.' }] }, [...headFields, repeater('items', 'Steps', [text('title', 'Step'), textarea('description', 'Description')])], Process),
  define('gallery', 'gallery', 'Filterable lookbook', { eyebrow: 'THE LOOKBOOK', heading: 'A little inspiration for your next chapter.', showFilters: true, buttonLabel: 'Plan your look', buttonUrl: '/appointment', items: [{ title: 'Soft movement', category: 'Styling', image: asset('gallery-1'), imageAlt: 'Salon hairstyle with soft movement' }, { title: 'Fresh dimension', category: 'Colour', image: asset('gallery-2'), imageAlt: 'Dimensional salon hair colour' }, { title: 'The finishing touch', category: 'Styling', image: asset('gallery-3'), imageAlt: 'Finished salon hairstyle' }] }, [...headFields, toggle('showFilters', 'Show category filters'), repeater('items', 'Photographs', [text('title', 'Caption'), text('category', 'Category'), ...photoFields]), ...cta], Gallery),
  define('team', 'team', 'Stylist profiles', { eyebrow: 'THE PEOPLE BEHIND THE CHAIR', heading: 'Creative minds.\nCaring hands.', detailsLabel: 'Meet your stylist', items: [{ title: 'Amelia Reed', role: 'Creative director', description: 'Amelia loves considered cuts, natural movement and helping people discover a style they enjoy wearing.', image: asset('team-1'), imageAlt: 'Veloura example creative director' }, { title: 'Theo James', role: 'Colour specialist', description: 'Theo brings a thoughtful eye for colour and dimension, with a plan for keeping your look fresh between visits.', image: asset('team-2'), imageAlt: 'Veloura example colour specialist' }, { title: 'Maya Ellis', role: 'Styling specialist', description: 'From easy everyday looks to special occasions, Maya makes room for the details that feel personal.', image: asset('team-3'), imageAlt: 'Veloura example styling specialist' }, { title: 'Luca Hayes', role: 'Hair-care specialist', description: 'Luca focuses on comfortable salon experiences and practical care that fits your daily routine.', image: asset('team-4'), imageAlt: 'Veloura example hair-care specialist' }] }, [...headFields, text('detailsLabel', 'Profile label'), repeater('items', 'Stylists', [text('title', 'Name'), text('role', 'Specialty'), textarea('description', 'Biography'), ...photoFields])], Team),
  define('testimonials', 'testimonials', 'Client story carousel', { ...dark, eyebrow: 'KIND WORDS', heading: 'The best part?\nHow you feel.', description: 'Example client stories — add your own salon reviews.', items: [{ quote: 'They took time to understand what I wanted and showed me how to style it myself. I left feeling completely at ease.', name: 'Alex R.', service: 'Cut & finish' }, { quote: 'A lovely, unhurried visit. My colour feels fresh and the advice was simple enough to use every day.', name: 'Sam K.', service: 'Colour & dimension' }, { quote: 'From the welcome to the final finish, every detail felt considered.', name: 'Jordan M.', service: 'Care & repair' }] }, [...headFields, repeater('items', 'Client stories', [textarea('quote', 'Review'), text('name', 'Client'), text('service', 'Service')])], Testimonials),
  define('pricing', 'pricing', 'Salon price menu', { pricePrefix: 'From', currency: '$', eyebrow: 'TIME WELL SPENT', heading: 'Find your perfect appointment.', description: 'Example starting prices. Your stylist confirms the final quote after discussing your hair, chosen service and appointment length.', buttonLabel: 'Ask about availability', buttonUrl: '/appointment', items: [...services.map(({ title, description, price }) => ({ title, description, price })), { title: 'Blow-dry & style', description: 'A polished finish for your everyday or a special occasion.', price: 40 }, { title: 'Occasion styling', description: 'A personal styling plan for your moment.', price: 90 }] }, [...headFields, ...cta, ...moneyFields, repeater('items', 'Price menu', [text('title', 'Service'), textarea('description', 'Description'), number('price', 'Price', 'content')])], Pricing),
  define('faq', 'faq', 'Appointment questions', { eyebrow: 'BEFORE YOUR VISIT', heading: 'A few things you might be wondering.', items: [{ question: 'How do I arrange an appointment?', answer: 'Send your preferred service and availability through the appointment form. The salon will reply to agree a time and confirm your visit.' }, { question: 'Can I talk to someone before choosing a service?', answer: 'Of course. Tell us what you have in mind and we will help you choose a starting point.' }, { question: 'How long should I allow?', answer: 'Timing depends on your chosen service and hair. We will confirm the expected duration when arranging your visit.' }, { question: 'Can I change my appointment?', answer: 'Contact the salon as soon as your plans change. The team will explain its cancellation policy and discuss another time.' }] }, [...headFields, repeater('items', 'Questions', [text('question', 'Question'), textarea('answer', 'Answer')])], Faq),
  define('cta', 'cta', 'Golden appointment invitation', { backgroundColor: '#f1c376', eyebrow: 'MAKE TIME FOR YOU', heading: 'Your next chapter looks good on you.', description: 'Let’s find a look you love living in.', buttonLabel: 'Book an appointment', buttonUrl: '/appointment' }, [...headFields, ...cta], p => <SectionShell props={p} className="vl vl-cta"><Head p={p} /><Button p={p} /></SectionShell>),
  define('form', 'form', 'Connected appointment inquiry', { eyebrow: 'COME SAY HELLO', heading: 'Let’s make a little time for you.', description: 'Tell us about the look you have in mind and when you would like to visit.', formId: '', formHeading: 'Request an appointment', buttonLabel: 'Send inquiry', note: 'This sends an inquiry. Your appointment is confirmed only when the salon replies.', items: [{ title: 'Visit the studio', value: 'Add your salon address in the editor', url: '' }, { title: 'Email', value: 'hello@veloura.example', url: 'mailto:hello@veloura.example' }, { title: 'Opening hours', value: 'Monday–Friday · 9am–7pm\nSaturday · 10am–6pm', url: '' }] }, [...headFields, text('formId', 'Connected form ID'), text('formHeading', 'Form heading'), text('buttonLabel', 'Submit label'), textarea('note', 'Confirmation note'), repeater('items', 'Contact information', [text('title', 'Label'), textarea('value', 'Value'), link('url', 'Link')]), ...columns], Contact),
  define('footer', 'footer', 'Multipage salon footer', { ...dark, brand: 'Veloura', logoUrl: '/', tagline: 'A fresh perspective. A look that feels like you.', copyright: '© 2026 Veloura. All rights reserved.', links, buttonLabel: 'Book a visit', buttonUrl: '/appointment' }, [text('brand', 'Brand'), ...logoImageFields, link('logoUrl', 'Logo link'), textarea('tagline', 'Tagline'), text('copyright', 'Copyright'), navLinksField(), ...cta], p => <SectionShell props={p} className="vl vl-footer"><div className="vl-footer-top"><div><a href={str(p.logoUrl, '/')} className="vl-brand"><BrandLogo props={p} alt={str(p.brand)}><Copy p={p} name="brand" as="span" /><span aria-hidden="true">✳</span></BrandLogo></a><Copy p={p} name="tagline" /></div><Button p={p} /></div><nav aria-label="Footer navigation">{items(p.links, []).map((row, i) => <a key={i} href={str(row.url)}><EditableText edit={editOf(p)} path={['links', i, 'label']} value={str(row.label)} as="span" /></a>)}</nav><Copy p={p} name="copyright" /></SectionShell>),
]



